-- ============================================================================
-- ROUND3-rabbis.sql — bnei-zion 1:1 parity, rabbi_page_items completion
-- Author: RABBI-RPI completion author (read-only scoping via sbq.py; this file
--         is EXECUTED BY THE ORCHESTRATOR, not by the author).
-- Generated by fixes/gen_round3_rabbis.py from old_rabbi_pages.json +
--   reports/verify_results.json + match/item_match.json + live SELECTs 2026-06-12.
-- Conventions (= apply stage + ROUND2 §3): rpi.sort_order = old rav-page row
--   index + 1 (1-based). Rows NOT on the old page are PARKED at 9000+ —
--   cross-attributed שו"ת keep their rabbis_plan slot (9000+old-idx on the
--   source page), double-apply duplicates get 9000+current-slot. NO DELETES.
-- All statements guarded/idempotent.
-- ============================================================================

-- ───────────────────────── §0 SIDE FIXES (titles / status / audience) ─────
-- title restore to the old rav-page display title
UPDATE lessons SET title = 'מגלות יהויכין עד חורבן הבית'
WHERE id = 'f1422687-d9a1-4bf2-a9aa-589b2e0cb676' AND title = 'מגלת יהויכין עד חורבן הבית';

-- title restore to the old rav-page display title
UPDATE lessons SET title = 'אם משה היה נכנס לארץ - האם התורה היתה ממשיכה להיכתב גם בארץ ישראל?'
WHERE id = '91bd2ced-488a-4796-af3c-67b2bd5f6020' AND title = 'אם משה היה נכנס לארץ - האם התורה הייתה ממשיכה להיכתב גם בארץ ישראל?';

-- title restore to the old rav-page display title
UPDATE lessons SET title = 'קיום מצוות מחיית עמלק במגילת אסתר'
WHERE id = '06adb28d-7d9a-4cf1-a43b-533f94fbacab' AND title = 'ושננתם, קיום מצוות מחיית עמלק במגילת אסתר';

-- series title restore to the old display title (old rav page + old public listings; current title appears on NO old surface)
UPDATE series SET title = 'הרב שלמה אבינר על פרשיות בראשית'
WHERE id = 'b2e079cd-15cf-4172-ab57-60b362f8e74c' AND title = 'הרב אבינר - שיחות על פרשיות בראשית';

-- series title restore to the old display title (old rav page + old public listings; current title appears on NO old surface)
UPDATE series SET title = 'הרב אבינר על פרשיות שמות'
WHERE id = '1f4cf5c3-8435-456e-bc08-17d05c8d7535' AND title = 'הרב אבינר - שיחות על פרשיות שמות';

-- series title restore to the old display title (old rav page + old public listings; current title appears on NO old surface)
UPDATE series SET title = 'הרב שלמה אבינר על פרשיות במדבר'
WHERE id = '6ba0b449-f49a-4414-9b74-dc6e3f97a149' AND title = 'הרב אבינר על פרשיות במדבר';

-- series title restore to the old display title (old rav page + old public listings; current title appears on NO old surface)
UPDATE series SET title = 'הרב שלמה אבינר על פרשיות במדבר'
WHERE id = 'd860d934-c76d-47d7-a988-5fe21358b3bd' AND title = 'הרב אבינר - שיחות על פרשיות במדבר';

-- publish: מגילת רות ויום מתן תורה, שער לקבלת התורה מרצון — old public rav-page row חגי #9
UPDATE lessons SET status = 'published' WHERE id = 'ff45f588-cc81-505f-9020-cbcb4d845a22' AND status = 'draft';

-- publish: ספר מלכים א עם ביאור 'ושננתם' — old public ושננתם row #14, legacy /media/142898/מלכים.pdf
UPDATE lessons SET status = 'published' WHERE id = 'e001f03e-8539-5533-8035-f8cf2035518b' AND status = 'draft';

-- audience union: על מה נצטוו ישראל במרה? — shown on the PUBLIC ושננתם old page (row #33) while live copy is teachers-only (ROUND2 §2 union precedent)
UPDATE lessons SET audience_tags = array_append(audience_tags, 'general')
WHERE id = '7dae3eca-08e8-4b32-8754-fa7e48568dd9' AND NOT ('general' = ANY(COALESCE(audience_tags, ARRAY[]::text[])));

-- ============================================================================
-- §הרב איתן שנדורפי  (rabbi_id be153d0e-b68e-4704-a108-56f5af7d0ca9)
--   old rows: 103 · live rpi: 124 · pairs: 102 · inserts: 0 · parks: 22 · yoav: 1 · sanctioned-missing: 0
-- ----------------------------------------------------------------------------
UPDATE rabbi_page_items SET sort_order = 9104 WHERE id = 'b62beaba-7da2-41fe-90d5-8bb00bba558c' AND sort_order = 104;  -- park 'בן נכר וסריסים' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9105 WHERE id = '23825913-e6f0-4f18-88e2-178bb3703cd0' AND sort_order = 105;  -- park 'נחלת זבולון' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9106 WHERE id = 'f02ecc3c-b40e-446b-b830-1c301967429d' AND sort_order = 106;  -- park 'קיום הברית עם רחב ומשפחתה' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9107 WHERE id = '1257d005-7068-46b5-868e-40c04ba8100e' AND sort_order = 107;  -- park 'דוד ואבישג' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9108 WHERE id = '8299aef4-21c6-4309-adb9-b0c060d7e539' AND sort_order = 108;  -- park 'מהות העגלים שהקים ירבעם' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9109 WHERE id = '73ec3eb8-4111-4112-8f88-e5180ae479b1' AND sort_order = 109;  -- park 'התנאי של אליהו לסיום הבצורת' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9110 WHERE id = 'b9d52a74-acd0-4576-9f33-70021f023cdb' AND sort_order = 110;  -- park '"ויהי ימים רבים"' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9111 WHERE id = '3856ad33-b917-4ab1-b8c8-793d5c1ee1b1' AND sort_order = 111;  -- park 'הזכרת שמות אמהות המלכים' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9112 WHERE id = '67d9dd45-11fa-4951-b179-cba70b9c2278' AND sort_order = 112;  -- park 'שמות אמהות מלכי יהודה' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9113 WHERE id = '59bd50d3-080c-4373-9938-fa692faa2b7f' AND sort_order = 113;  -- park 'אורך התקופה של ספר מלכים' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9114 WHERE id = 'fefcf7a0-90dc-46d4-8feb-b182db8e465b' AND sort_order = 114;  -- park 'הכותים, האריות שד'' שלח בהם, וכיצד הוסרו האריות' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9115 WHERE id = '5a2d7507-80a5-4317-a831-3f5a4766bd97' AND sort_order = 115;  -- park 'מדוע שרו ישראל בשירת דבורה' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9116 WHERE id = '56a7f5df-4116-4e50-b7e4-1c08f189543b' AND sort_order = 116;  -- park 'האם ישי ובניו הבינו ששמואל בא למשוח את דוד' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9117 WHERE id = '374efbb3-e597-433c-b272-613e3c5d76f6' AND sort_order = 117;  -- park 'הר אפרים ובית לחם יהודה' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9118 WHERE id = '8f00c43c-86f7-4392-a364-4200bca012b2' AND sort_order = 118;  -- park 'כיצד להבין את חטאי שאול' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9119 WHERE id = 'db03a576-afe1-4ac4-a420-a762a6cf5d93' AND sort_order = 119;  -- park 'כמה שאלות בספר שמואל ובשופטים' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9120 WHERE id = '3610330d-fcfb-461b-b0a5-a153114c7d4f' AND sort_order = 120;  -- park 'האם היה מותר לדוד להרוג את נבל הכרמלי?' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9121 WHERE id = 'b40e52c7-5e2b-4774-ad50-06f3cd59d6dc' AND sort_order = 121;  -- park 'יונתן ונערו במלחמת פלשתים' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9122 WHERE id = 'a5af470e-1859-4eb1-be89-91d94c9133cf' AND sort_order = 122;  -- park 'שאול ויונתן במלחמת פלשתים' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9123 WHERE id = '6cde1805-73be-4266-8e17-562ecf6410c2' AND sort_order = 123;  -- park 'יואב בן צרויה' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9124 WHERE id = '9fc6f084-9833-4b11-a198-147fe7116788' AND sort_order = 124;  -- park 'הריגת צאצאי שאול בידי דוד' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9125 WHERE id = 'abefd006-c653-49f2-8959-1857ed731fad' AND sort_order = 125;  -- park 'מלחמות דוד בספר שמואל ב'' פרק ח'' לעומת חטא דוד בפ' (not on the old rav page (double-apply dup / deliberate addition) — parked)

-- verification: in-band ladder size (expect 102; old rows 103 minus 1 yoav minus 0 sanctioned-missing)
SELECT count(*) AS v_be153d0e_inband FROM rabbi_page_items WHERE rabbi_id = 'be153d0e-b68e-4704-a108-56f5af7d0ca9' AND sort_order < 9000;
-- verification: parked rows (expect 22)
SELECT count(*) AS v_be153d0e_parked FROM rabbi_page_items WHERE rabbi_id = 'be153d0e-b68e-4704-a108-56f5af7d0ca9' AND sort_order >= 9000;
-- verification: no in-band slot collisions (expect 0)
SELECT count(*) AS v_be153d0e_collisions FROM (SELECT sort_order FROM rabbi_page_items WHERE rabbi_id='be153d0e-b68e-4704-a108-56f5af7d0ca9' AND sort_order<9000 GROUP BY sort_order HAVING count(*)>1) q;

-- ============================================================================
-- §הרב אס"ף בנדל  (rabbi_id 723c69b7-a119-42f5-9684-c4a05388475a)
--   old rows: 15 · live rpi: 20 · pairs: 14 · inserts: 1 · parks: 6 · yoav: 0 · sanctioned-missing: 0
-- ----------------------------------------------------------------------------
-- old row #12 'תלונות על הקב"ה בתנ"ך'
INSERT INTO rabbi_page_items (rabbi_id, kind, lesson_id, sort_order)
SELECT '723c69b7-a119-42f5-9684-c4a05388475a', 'qa', '9f29a034-6f0f-46fb-a4f7-d8053cfa4835', 13
WHERE NOT EXISTS (SELECT 1 FROM rabbi_page_items WHERE rabbi_id='723c69b7-a119-42f5-9684-c4a05388475a' AND lesson_id='9f29a034-6f0f-46fb-a4f7-d8053cfa4835' AND sort_order=13);

UPDATE rabbi_page_items SET sort_order = 9016 WHERE id = '7ebf127b-aba7-4a9a-b8a0-36ab0cef898b' AND sort_order = 16;  -- park 'לימוד חטאי בית ראשון בדורינו' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9017 WHERE id = 'cbcf0a85-45d7-4e4b-9dfd-859f8156b26e' AND sort_order = 17;  -- park 'פתחון פיו של יחזקאל' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9018 WHERE id = 'd03ea5fe-4cdf-44fc-871f-7024e81a7739' AND sort_order = 18;  -- park 'בין משכן למקדש' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9019 WHERE id = '75057f59-1fab-49aa-9e8d-10725da653f2' AND sort_order = 19;  -- park 'שהות דוד בארץ פלשתים' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9020 WHERE id = '06fd76ab-704d-434e-9f85-429077149769' AND sort_order = 20;  -- park 'עשהאל ואבנר' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9021 WHERE id = '63138940-f737-4691-bc20-9a1ecbeb7c22' AND sort_order = 21;  -- park 'דוד ואנשי יבש גלעד' (not on the old rav page (double-apply dup / deliberate addition) — parked)

-- verification: in-band ladder size (expect 15; old rows 15 minus 0 yoav minus 0 sanctioned-missing)
SELECT count(*) AS v_723c69b7_inband FROM rabbi_page_items WHERE rabbi_id = '723c69b7-a119-42f5-9684-c4a05388475a' AND sort_order < 9000;
-- verification: parked rows (expect 6)
SELECT count(*) AS v_723c69b7_parked FROM rabbi_page_items WHERE rabbi_id = '723c69b7-a119-42f5-9684-c4a05388475a' AND sort_order >= 9000;
-- verification: no in-band slot collisions (expect 0)
SELECT count(*) AS v_723c69b7_collisions FROM (SELECT sort_order FROM rabbi_page_items WHERE rabbi_id='723c69b7-a119-42f5-9684-c4a05388475a' AND sort_order<9000 GROUP BY sort_order HAVING count(*)>1) q;

-- ============================================================================
-- §הרב אריה אברמסון  (rabbi_id f3cb36a5-ce6f-453d-939b-37a987b2fd9d)
--   old rows: 5 · live rpi: 5 · pairs: 5 · inserts: 0 · parks: 0 · yoav: 0 · sanctioned-missing: 0
-- ----------------------------------------------------------------------------
-- verification: in-band ladder size (expect 5; old rows 5 minus 0 yoav minus 0 sanctioned-missing)
SELECT count(*) AS v_f3cb36a5_inband FROM rabbi_page_items WHERE rabbi_id = 'f3cb36a5-ce6f-453d-939b-37a987b2fd9d' AND sort_order < 9000;
-- verification: parked rows (expect 0)
SELECT count(*) AS v_f3cb36a5_parked FROM rabbi_page_items WHERE rabbi_id = 'f3cb36a5-ce6f-453d-939b-37a987b2fd9d' AND sort_order >= 9000;
-- verification: no in-band slot collisions (expect 0)
SELECT count(*) AS v_f3cb36a5_collisions FROM (SELECT sort_order FROM rabbi_page_items WHERE rabbi_id='f3cb36a5-ce6f-453d-939b-37a987b2fd9d' AND sort_order<9000 GROUP BY sort_order HAVING count(*)>1) q;

-- ============================================================================
-- §הרב אריק אוריאל  (rabbi_id 34ef8dae-5352-4dfe-9887-ab7c3b8bcdd8)
--   old rows: 3 · live rpi: 5 · pairs: 3 · inserts: 0 · parks: 2 · yoav: 0 · sanctioned-missing: 0
-- ----------------------------------------------------------------------------
UPDATE rabbi_page_items SET sort_order = 9000 WHERE id = '861439d9-f982-4dac-bc2e-766bc2258137' AND sort_order = 4;  -- park 'כתבי הקודש - מעטפה ותוכן' (cross-attributed שו"ת — sanctioned rabbis_plan slot)
UPDATE rabbi_page_items SET sort_order = 9001 WHERE id = 'efa878db-7333-4ab7-b836-be565a626d5a' AND sort_order = 5;  -- park 'על סיפה של מלחמת אחים' (cross-attributed שו"ת — sanctioned rabbis_plan slot)

-- verification: in-band ladder size (expect 3; old rows 3 minus 0 yoav minus 0 sanctioned-missing)
SELECT count(*) AS v_34ef8dae_inband FROM rabbi_page_items WHERE rabbi_id = '34ef8dae-5352-4dfe-9887-ab7c3b8bcdd8' AND sort_order < 9000;
-- verification: parked rows (expect 2)
SELECT count(*) AS v_34ef8dae_parked FROM rabbi_page_items WHERE rabbi_id = '34ef8dae-5352-4dfe-9887-ab7c3b8bcdd8' AND sort_order >= 9000;
-- verification: no in-band slot collisions (expect 0)
SELECT count(*) AS v_34ef8dae_collisions FROM (SELECT sort_order FROM rabbi_page_items WHERE rabbi_id='34ef8dae-5352-4dfe-9887-ab7c3b8bcdd8' AND sort_order<9000 GROUP BY sort_order HAVING count(*)>1) q;

-- ============================================================================
-- §הרב חגי ולוסקי  (rabbi_id b28770d5-1504-46ad-8613-3c3ca37a641c)
--   old rows: 10 · live rpi: 4 · pairs: 4 · inserts: 6 · parks: 0 · yoav: 0 · sanctioned-missing: 0
-- ----------------------------------------------------------------------------
UPDATE rabbi_page_items SET sort_order = 2 WHERE id = 'ccee1d1e-ae5a-4d20-a471-eec16d93437b' AND sort_order <> 2;  -- old #1 'מידות בפרשה'
UPDATE rabbi_page_items SET sort_order = 7 WHERE id = '62cda6c0-c56d-4abe-91f6-b35de9f9df88' AND sort_order <> 7;  -- old #6 'עבדו את ה'' בשמחה'
UPDATE rabbi_page_items SET sort_order = 8 WHERE id = '2dab7b31-7be6-4d56-ad22-1e336298c2c3' AND sort_order <> 8;  -- old #7 'מגילת אסתר – מגילת הַסֵּתֶר'
UPDATE rabbi_page_items SET sort_order = 9 WHERE id = '2115b89e-4662-4f53-8280-1572ba9b0d79' AND sort_order <> 9;  -- old #8 'המהפך ההיסטורי – שיעור בעוצמה מנהיגותית'

-- old row #0 'מידות בפרשה'
INSERT INTO rabbi_page_items (rabbi_id, kind, series_id, sort_order)
SELECT 'b28770d5-1504-46ad-8613-3c3ca37a641c', 'series', '8755bfbb-ae30-44d5-87e3-af5eaf4ddd25', 1
WHERE NOT EXISTS (SELECT 1 FROM rabbi_page_items WHERE rabbi_id='b28770d5-1504-46ad-8613-3c3ca37a641c' AND series_id='8755bfbb-ae30-44d5-87e3-af5eaf4ddd25' AND sort_order=1);

-- old row #2 'מידות בפרשה'
INSERT INTO rabbi_page_items (rabbi_id, kind, series_id, sort_order)
SELECT 'b28770d5-1504-46ad-8613-3c3ca37a641c', 'series', '23ba1703-6509-41fb-a69c-c4bd85d8a5d0', 3
WHERE NOT EXISTS (SELECT 1 FROM rabbi_page_items WHERE rabbi_id='b28770d5-1504-46ad-8613-3c3ca37a641c' AND series_id='23ba1703-6509-41fb-a69c-c4bd85d8a5d0' AND sort_order=3);

-- old row #3 'מידות בפרשה'
INSERT INTO rabbi_page_items (rabbi_id, kind, series_id, sort_order)
SELECT 'b28770d5-1504-46ad-8613-3c3ca37a641c', 'series', 'dfb8c480-35cd-4e8c-9f1d-a3a4c2666213', 4
WHERE NOT EXISTS (SELECT 1 FROM rabbi_page_items WHERE rabbi_id='b28770d5-1504-46ad-8613-3c3ca37a641c' AND series_id='dfb8c480-35cd-4e8c-9f1d-a3a4c2666213' AND sort_order=4);

-- old row #4 'מידות בפרשה'
INSERT INTO rabbi_page_items (rabbi_id, kind, series_id, sort_order)
SELECT 'b28770d5-1504-46ad-8613-3c3ca37a641c', 'series', 'b87f2a49-5e27-40ab-bb7d-e22f5bbc3de0', 5
WHERE NOT EXISTS (SELECT 1 FROM rabbi_page_items WHERE rabbi_id='b28770d5-1504-46ad-8613-3c3ca37a641c' AND series_id='b87f2a49-5e27-40ab-bb7d-e22f5bbc3de0' AND sort_order=5);

-- old row #5 'מגילת אסתר – מגילת הסתר'
INSERT INTO rabbi_page_items (rabbi_id, kind, lesson_id, sort_order)
SELECT 'b28770d5-1504-46ad-8613-3c3ca37a641c', 'lesson', 'af593ccf-0e6f-5602-be6b-d6f744888783', 6
WHERE NOT EXISTS (SELECT 1 FROM rabbi_page_items WHERE rabbi_id='b28770d5-1504-46ad-8613-3c3ca37a641c' AND lesson_id='af593ccf-0e6f-5602-be6b-d6f744888783' AND sort_order=6);

-- old row #9 'מגילת רות ויום מתן תורה, שער לקבלת התורה מרצון'
INSERT INTO rabbi_page_items (rabbi_id, kind, lesson_id, sort_order)
SELECT 'b28770d5-1504-46ad-8613-3c3ca37a641c', 'lesson', 'ff45f588-cc81-505f-9020-cbcb4d845a22', 10
WHERE NOT EXISTS (SELECT 1 FROM rabbi_page_items WHERE rabbi_id='b28770d5-1504-46ad-8613-3c3ca37a641c' AND lesson_id='ff45f588-cc81-505f-9020-cbcb4d845a22' AND sort_order=10);

-- verification: in-band ladder size (expect 10; old rows 10 minus 0 yoav minus 0 sanctioned-missing)
SELECT count(*) AS v_b28770d5_inband FROM rabbi_page_items WHERE rabbi_id = 'b28770d5-1504-46ad-8613-3c3ca37a641c' AND sort_order < 9000;
-- verification: parked rows (expect 0)
SELECT count(*) AS v_b28770d5_parked FROM rabbi_page_items WHERE rabbi_id = 'b28770d5-1504-46ad-8613-3c3ca37a641c' AND sort_order >= 9000;
-- verification: no in-band slot collisions (expect 0)
SELECT count(*) AS v_b28770d5_collisions FROM (SELECT sort_order FROM rabbi_page_items WHERE rabbi_id='b28770d5-1504-46ad-8613-3c3ca37a641c' AND sort_order<9000 GROUP BY sort_order HAVING count(*)>1) q;

-- ============================================================================
-- §הרב יהונתן מיכאלי  (rabbi_id 3a3eac56-4546-4803-9d38-1fceb0c1452d)
--   old rows: 5 · live rpi: 1 · pairs: 1 · inserts: 4 · parks: 0 · yoav: 0 · sanctioned-missing: 0
-- ----------------------------------------------------------------------------
UPDATE rabbi_page_items SET sort_order = 2 WHERE id = '00452322-8cb9-41e6-b9b5-3c1d424e8c95' AND sort_order <> 2;  -- old #1 'לשון הקודש בפרשה'

-- old row #0 'לשון הקודש בפרשה'
INSERT INTO rabbi_page_items (rabbi_id, kind, series_id, sort_order)
SELECT '3a3eac56-4546-4803-9d38-1fceb0c1452d', 'series', 'd6260ade-6c3d-4f5c-956b-c043504fd055', 1
WHERE NOT EXISTS (SELECT 1 FROM rabbi_page_items WHERE rabbi_id='3a3eac56-4546-4803-9d38-1fceb0c1452d' AND series_id='d6260ade-6c3d-4f5c-956b-c043504fd055' AND sort_order=1);

-- old row #2 'לשון הקודש בפרשה'
INSERT INTO rabbi_page_items (rabbi_id, kind, series_id, sort_order)
SELECT '3a3eac56-4546-4803-9d38-1fceb0c1452d', 'series', '3479554b-8826-4f1d-8894-b70dd9709780', 3
WHERE NOT EXISTS (SELECT 1 FROM rabbi_page_items WHERE rabbi_id='3a3eac56-4546-4803-9d38-1fceb0c1452d' AND series_id='3479554b-8826-4f1d-8894-b70dd9709780' AND sort_order=3);

-- old row #3 'לשון הקודש בפרשה'
INSERT INTO rabbi_page_items (rabbi_id, kind, series_id, sort_order)
SELECT '3a3eac56-4546-4803-9d38-1fceb0c1452d', 'series', '9fd0779c-c564-4b03-8409-b1d3b20e7afb', 4
WHERE NOT EXISTS (SELECT 1 FROM rabbi_page_items WHERE rabbi_id='3a3eac56-4546-4803-9d38-1fceb0c1452d' AND series_id='9fd0779c-c564-4b03-8409-b1d3b20e7afb' AND sort_order=4);

-- old row #4 'לשון הקודש בפרשה'
INSERT INTO rabbi_page_items (rabbi_id, kind, series_id, sort_order)
SELECT '3a3eac56-4546-4803-9d38-1fceb0c1452d', 'series', 'a64f6c91-4e4c-48f0-a9c2-91e0319b817e', 5
WHERE NOT EXISTS (SELECT 1 FROM rabbi_page_items WHERE rabbi_id='3a3eac56-4546-4803-9d38-1fceb0c1452d' AND series_id='a64f6c91-4e4c-48f0-a9c2-91e0319b817e' AND sort_order=5);

-- verification: in-band ladder size (expect 5; old rows 5 minus 0 yoav minus 0 sanctioned-missing)
SELECT count(*) AS v_3a3eac56_inband FROM rabbi_page_items WHERE rabbi_id = '3a3eac56-4546-4803-9d38-1fceb0c1452d' AND sort_order < 9000;
-- verification: parked rows (expect 0)
SELECT count(*) AS v_3a3eac56_parked FROM rabbi_page_items WHERE rabbi_id = '3a3eac56-4546-4803-9d38-1fceb0c1452d' AND sort_order >= 9000;
-- verification: no in-band slot collisions (expect 0)
SELECT count(*) AS v_3a3eac56_collisions FROM (SELECT sort_order FROM rabbi_page_items WHERE rabbi_id='3a3eac56-4546-4803-9d38-1fceb0c1452d' AND sort_order<9000 GROUP BY sort_order HAVING count(*)>1) q;

-- ============================================================================
-- §הרב יהונתן עידן  (rabbi_id b545bcbd-97a8-482e-a69f-6b7e1ed3c939)
--   old rows: 3 · live rpi: 1 · pairs: 1 · inserts: 2 · parks: 0 · yoav: 0 · sanctioned-missing: 0
-- ----------------------------------------------------------------------------
UPDATE rabbi_page_items SET sort_order = 2 WHERE id = '0d7f2e4b-2063-4f22-bb9b-e75f6faec82d' AND sort_order <> 2;  -- old #1 'הארות באונקלוס'

-- old row #0 'הארות באונקלוס'
INSERT INTO rabbi_page_items (rabbi_id, kind, series_id, sort_order)
SELECT 'b545bcbd-97a8-482e-a69f-6b7e1ed3c939', 'series', '62cc9e36-ed77-4dd5-b14e-93124b50f08f', 1
WHERE NOT EXISTS (SELECT 1 FROM rabbi_page_items WHERE rabbi_id='b545bcbd-97a8-482e-a69f-6b7e1ed3c939' AND series_id='62cc9e36-ed77-4dd5-b14e-93124b50f08f' AND sort_order=1);

-- old row #2 'הארות באונקלוס'
INSERT INTO rabbi_page_items (rabbi_id, kind, series_id, sort_order)
SELECT 'b545bcbd-97a8-482e-a69f-6b7e1ed3c939', 'series', '5a466b5c-cec2-477d-9bd9-5100e13218ad', 3
WHERE NOT EXISTS (SELECT 1 FROM rabbi_page_items WHERE rabbi_id='b545bcbd-97a8-482e-a69f-6b7e1ed3c939' AND series_id='5a466b5c-cec2-477d-9bd9-5100e13218ad' AND sort_order=3);

-- verification: in-band ladder size (expect 3; old rows 3 minus 0 yoav minus 0 sanctioned-missing)
SELECT count(*) AS v_b545bcbd_inband FROM rabbi_page_items WHERE rabbi_id = 'b545bcbd-97a8-482e-a69f-6b7e1ed3c939' AND sort_order < 9000;
-- verification: parked rows (expect 0)
SELECT count(*) AS v_b545bcbd_parked FROM rabbi_page_items WHERE rabbi_id = 'b545bcbd-97a8-482e-a69f-6b7e1ed3c939' AND sort_order >= 9000;
-- verification: no in-band slot collisions (expect 0)
SELECT count(*) AS v_b545bcbd_collisions FROM (SELECT sort_order FROM rabbi_page_items WHERE rabbi_id='b545bcbd-97a8-482e-a69f-6b7e1ed3c939' AND sort_order<9000 GROUP BY sort_order HAVING count(*)>1) q;

-- ============================================================================
-- §הרב יואב אוריאל  (rabbi_id acd34d0f-1288-47b8-9e8e-38e69599c294)
--   old rows: 144 · live rpi: 164 · pairs: 138 · inserts: 1 · parks: 26 · yoav: 0 · sanctioned-missing: 5
-- ----------------------------------------------------------------------------
UPDATE rabbi_page_items SET sort_order = 112 WHERE id = '5310a8c9-95f0-430f-8268-a552eb75e6c2' AND sort_order <> 112;  -- old #111 'ניצחון דוד את הארי והדוב'
UPDATE rabbi_page_items SET sort_order = 113 WHERE id = '9b8016e8-ad39-48a0-94c8-0a8285121521' AND sort_order <> 113;  -- old #112 'התחיה המפתיעה של עמלק'
UPDATE rabbi_page_items SET sort_order = 114 WHERE id = '1f67f53f-6121-4439-8c5f-2b7ca265e710' AND sort_order <> 114;  -- old #113 'הרצון למנות מלך ומלחמת בני עמון'
UPDATE rabbi_page_items SET sort_order = 115 WHERE id = 'f4b6a3bf-3574-450f-bcf0-e93ae328f400' AND sort_order <> 115;  -- old #114 'וישסף שמואל את אגג'
UPDATE rabbi_page_items SET sort_order = 116 WHERE id = '20f71da3-cea4-424d-80cf-f043ab143235' AND sort_order <> 116;  -- old #115 'מדוע הומלך שאול שלוש פעמים?'
UPDATE rabbi_page_items SET sort_order = 117 WHERE id = '2a42b2f1-cf55-4156-84ca-3db886e08b1f' AND sort_order <> 117;  -- old #116 'יהונתן בן שמעה אחי דוד'
UPDATE rabbi_page_items SET sort_order = 118 WHERE id = '7a640e5c-6f2b-4094-8a8a-d0f934269177' AND sort_order <> 118;  -- old #117 'השבט שאליו השתייכה בת שבע'
UPDATE rabbi_page_items SET sort_order = 119 WHERE id = 'b1be05e1-d402-4cba-9ee7-b35b31e4916d' AND sort_order <> 119;  -- old #118 'הריגת שבעת בני שאול בידי הגבעונים'
UPDATE rabbi_page_items SET sort_order = 120 WHERE id = '92eb24f0-16ac-4d97-8c0d-178720feea2e' AND sort_order <> 120;  -- old #119 'השיוך השבטי של נשות דוד'
UPDATE rabbi_page_items SET sort_order = 121 WHERE id = '0d295532-107f-46b0-a739-8db8114af535' AND sort_order <> 121;  -- old #120 'הקדמות למעשה דוד ובת שבע'
UPDATE rabbi_page_items SET sort_order = 122 WHERE id = '834c6fc5-4db8-4375-a3c0-738b17bd8e97' AND sort_order <> 122;  -- old #121 'מגמתו של אבנר בן נר'
UPDATE rabbi_page_items SET sort_order = 123 WHERE id = '0a39a512-fa04-46d5-a29a-8914de081b28' AND sort_order <> 123;  -- old #122 'המתת צאצאי שאול בידי הגבעונים'
UPDATE rabbi_page_items SET sort_order = 124 WHERE id = 'b6f74a09-9187-4588-826c-33598dfb2b67' AND sort_order <> 124;  -- old #123 'אליהו הנביא: מלמד זכות או חובה על ישראל?'
UPDATE rabbi_page_items SET sort_order = 125 WHERE id = '9ee96496-02f1-4c11-9754-e4c8ba1cad77' AND sort_order <> 125;  -- old #124 'לאיזו מלכות היה שייך שבט שמעון?'
UPDATE rabbi_page_items SET sort_order = 126 WHERE id = '7d610154-af21-4eff-ac84-885724b8f5ff' AND sort_order <> 126;  -- old #125 'הניסים הפרטיים שעשה אלישע'
UPDATE rabbi_page_items SET sort_order = 127 WHERE id = '93e9d041-5bb8-4b1d-9d77-96d1b6895634' AND sort_order <> 127;  -- old #126 'עבודה זרה וגאוה'
UPDATE rabbi_page_items SET sort_order = 128 WHERE id = '60bb6c8a-951a-4a70-b12e-683760ba0338' AND sort_order <> 128;  -- old #127 'ישעיהו כולו נחמה'
UPDATE rabbi_page_items SET sort_order = 129 WHERE id = 'bb7e83ff-a90c-420b-8c82-ccb7deed8814' AND sort_order <> 129;  -- old #128 'תקופת עבודת הבעל'
UPDATE rabbi_page_items SET sort_order = 130 WHERE id = '97b78cad-1add-4e49-85b9-980861e55a22' AND sort_order <> 130;  -- old #129 'התפקיד ההיסטורי של חגי הנביא'
UPDATE rabbi_page_items SET sort_order = 131 WHERE id = 'a07b25c7-789e-43dc-86b3-ed645583af7e' AND sort_order <> 131;  -- old #130 'האם יש נבואה מפורשת המייעדת על ניצחון היהודים על'
UPDATE rabbi_page_items SET sort_order = 133 WHERE id = 'c8caeb17-ae4b-4097-82e2-3c9b57b65900' AND sort_order <> 133;  -- old #132 'בין פרשת ויקרא לפרשת צו'
UPDATE rabbi_page_items SET sort_order = 134 WHERE id = 'ff170a18-cb45-470f-9d5b-f3db087ce649' AND sort_order <> 134;  -- old #133 '"ישמחו השמים ותגל הארץ" - מדוע הם שמחים?'
UPDATE rabbi_page_items SET sort_order = 135 WHERE id = '9775670a-df3e-4dba-8d44-dd752b40c024' AND sort_order <> 135;  -- old #134 'השתהות בועז'
UPDATE rabbi_page_items SET sort_order = 136 WHERE id = 'c31ab36e-e64e-4d75-88b8-fc9230a29833' AND sort_order <> 136;  -- old #135 'שני החלומות על ארבע המלכויות'
UPDATE rabbi_page_items SET sort_order = 137 WHERE id = 'ffdd0166-028b-4cf2-b75d-3a1eb83fe284' AND sort_order <> 137;  -- old #136 'הקץ של דניאל - חותם הקיצים בתנ"ך'
UPDATE rabbi_page_items SET sort_order = 139 WHERE id = '842d1bd0-168e-4016-8a7f-cadd0742bd44' AND sort_order <> 139;  -- old #138 'שאלת איסור הבמות'
UPDATE rabbi_page_items SET sort_order = 142 WHERE id = 'e49fc208-67c2-4514-abb5-d0b28d0a98d8' AND sort_order <> 142;  -- old #141 'תולדות הכניסה לארץ: מדרום או ממזרח'
UPDATE rabbi_page_items SET sort_order = 143 WHERE id = '7ad759ac-5b18-46d4-bb74-a1b1b88964a4' AND sort_order <> 143;  -- old #142 'הציווי הכפול על משה לעלות להר העברים'
UPDATE rabbi_page_items SET sort_order = 144 WHERE id = '77d59a08-702b-439e-b67c-78f42ad7802e' AND sort_order <> 144;  -- old #143 'רשימת המקומות בתחילת פרשת דברים'

-- old row #80 'שלוש החנוכות של חודש כסליו'
INSERT INTO rabbi_page_items (rabbi_id, kind, lesson_id, sort_order)
SELECT 'acd34d0f-1288-47b8-9e8e-38e69599c294', 'lesson', 'ba84d404-de05-486c-85f8-390a41484e83', 81
WHERE NOT EXISTS (SELECT 1 FROM rabbi_page_items WHERE rabbi_id='acd34d0f-1288-47b8-9e8e-38e69599c294' AND lesson_id='ba84d404-de05-486c-85f8-390a41484e83' AND sort_order=81);

UPDATE rabbi_page_items SET sort_order = 9140 WHERE id = '13df1a63-0169-4576-bb60-a7e60a365007' AND sort_order = 140;  -- park 'עבודה זרה וגאוה' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9141 WHERE id = 'f9df3fe8-3f88-4468-8ce5-07c8fdb7eaaa' AND sort_order = 141;  -- park 'ישעיהו כולו נחמה' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9142 WHERE id = '95136a80-cfa6-4580-9166-d557c9a0b8e2' AND sort_order = 142;  -- park 'תקופת עבודת הבעל' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9143 WHERE id = '1302dbdd-b6c3-423f-b08f-ff9b9026998d' AND sort_order = 143;  -- park 'רש"י הראשון על התורה והנ"ך' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9144 WHERE id = '0fa9cae0-65f0-4016-98e7-9839ed08794c' AND sort_order = 144;  -- park 'מדוע לא השלים יהושע את כיבוש הארץ?' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9145 WHERE id = '826929f4-98a4-4987-a55a-e8e00ddb578d' AND sort_order = 145;  -- park 'התפקיד ההיסטורי של חגי הנביא' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9146 WHERE id = 'f92e5209-bc43-4c5f-bebd-da426f012b2e' AND sort_order = 146;  -- park 'המלכים שהיכה יהושע - ומלך חברון' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9147 WHERE id = '14feaf85-567e-48aa-8b02-69c5c4dc721c' AND sort_order = 147;  -- park 'האם יש נבואה מפורשת המייעדת על ניצחון היהודים על' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9148 WHERE id = '915720d5-b5e1-4415-ad79-aeb356997534' AND sort_order = 148;  -- park 'תפקיד יהושע בפרשת המזבח' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9149 WHERE id = '03d43d25-4eb9-48bc-b6e0-a09a72aa1ad4' AND sort_order = 149;  -- park 'אי הכרתת הענקים מערי פלשתים' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9150 WHERE id = 'f924f2a7-96c3-4c89-959d-c6380f7f11a1' AND sort_order = 150;  -- park 'אליהו הנביא: מלמד זכות או חובה על ישראל?' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9151 WHERE id = '6bad4e78-5b97-48e4-84f0-9975132187b0' AND sort_order = 151;  -- park 'לאיזו מלכות היה שייך שבט שמעון?' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9152 WHERE id = '6f6ab04f-8f34-40e7-aeb4-8ab4ee8106e8' AND sort_order = 152;  -- park 'הניסים הפרטיים שעשה אלישע' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9153 WHERE id = 'a1fb180c-1155-4b4d-8611-32f54916024a' AND sort_order = 153;  -- park 'חזרת מעשה עתניאל ועכסה ביהושע ובשופטים' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9154 WHERE id = 'f26842e1-7d77-4bfb-8d92-09fbd4cebda3' AND sort_order = 154;  -- park 'איך הגיעו ישראל לשפל של פילגש בגבעה?' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9155 WHERE id = '8391540c-2de2-49f3-bfcb-9f59696c6d19' AND sort_order = 155;  -- park 'ניצחון דוד את הארי והדוב' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9156 WHERE id = '5bf524e7-7cbe-4fef-8916-17a8525346c6' AND sort_order = 156;  -- park 'התחיה המפתיעה של עמלק' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9157 WHERE id = '1e0b9210-b9e8-4850-b76c-4fb9a363a220' AND sort_order = 157;  -- park 'הרצון למנות מלך ומלחמת בני עמון' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9158 WHERE id = 'ce2d2753-7cf6-4127-bc3e-5e5515e8382b' AND sort_order = 158;  -- park 'וישסף שמואל את אגג' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9159 WHERE id = 'f783a4c6-1a02-418c-a94d-1e06a90c8489' AND sort_order = 159;  -- park 'מדוע הומלך שאול שלוש פעמים?' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9160 WHERE id = '87406c77-704a-410f-9fea-758a66f11653' AND sort_order = 160;  -- park 'יהונתן בן שמעה אחי דוד' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9161 WHERE id = 'b48c576e-f910-4700-ad23-174df46c8a3d' AND sort_order = 161;  -- park 'השבט שאליו השתייכה בת שבע' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9162 WHERE id = '2399c318-34c3-46c8-8a7f-fc076a674b47' AND sort_order = 162;  -- park 'הריגת שבעת בני שאול בידי הגבעונים' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9163 WHERE id = 'e198fba2-623e-4619-a3e9-8f79c9f9aed6' AND sort_order = 163;  -- park 'השיוך השבטי של נשות דוד' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9164 WHERE id = '3f82c686-313b-4d75-b96d-0d3e05e54fa1' AND sort_order = 164;  -- park 'מגמתו של אבנר בן נר' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9165 WHERE id = '65252ef8-daf3-4f87-bc69-785645c9764c' AND sort_order = 165;  -- park 'המתת צאצאי שאול בידי הגבעונים' (not on the old rav page (double-apply dup / deliberate addition) — parked)

-- verification: in-band ladder size (expect 139; old rows 144 minus 0 yoav minus 5 sanctioned-missing)
SELECT count(*) AS v_acd34d0f_inband FROM rabbi_page_items WHERE rabbi_id = 'acd34d0f-1288-47b8-9e8e-38e69599c294' AND sort_order < 9000;
-- verification: parked rows (expect 26)
SELECT count(*) AS v_acd34d0f_parked FROM rabbi_page_items WHERE rabbi_id = 'acd34d0f-1288-47b8-9e8e-38e69599c294' AND sort_order >= 9000;
-- verification: no in-band slot collisions (expect 0)
SELECT count(*) AS v_acd34d0f_collisions FROM (SELECT sort_order FROM rabbi_page_items WHERE rabbi_id='acd34d0f-1288-47b8-9e8e-38e69599c294' AND sort_order<9000 GROUP BY sort_order HAVING count(*)>1) q;

-- ============================================================================
-- §הרב יוסי ברינר  (rabbi_id d68b38ad-fd70-47d3-b667-20f68af6d8c4)
--   old rows: 31 · live rpi: 46 · pairs: 30 · inserts: 1 · parks: 16 · yoav: 0 · sanctioned-missing: 0
-- ----------------------------------------------------------------------------
-- old row #26 'פתיחת למנצח במזמורי תהילים'
INSERT INTO rabbi_page_items (rabbi_id, kind, lesson_id, sort_order)
SELECT 'd68b38ad-fd70-47d3-b667-20f68af6d8c4', 'qa', '24e8524c-fb6c-4896-8564-e2bfd10be3ad', 27
WHERE NOT EXISTS (SELECT 1 FROM rabbi_page_items WHERE rabbi_id='d68b38ad-fd70-47d3-b667-20f68af6d8c4' AND lesson_id='24e8524c-fb6c-4896-8564-e2bfd10be3ad' AND sort_order=27);

UPDATE rabbi_page_items SET sort_order = 9032 WHERE id = 'cce7f8f9-449a-4ca2-a051-fa66574b1b00' AND sort_order = 32;  -- park 'ציון וירושלים' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9033 WHERE id = '20bf03ca-7af8-4d9b-b649-dd51f1d977d3' AND sort_order = 33;  -- park 'שארית הפליטה לאחר חורבן בית ראשון' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9034 WHERE id = '0945e468-7882-42d3-8011-c3f054f8bfbb' AND sort_order = 34;  -- park 'נבואות ירמיהו על הגויים' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9035 WHERE id = '9cfb14f3-5585-43e9-bb68-d59a43c7fa2a' AND sort_order = 35;  -- park 'האם פנחס הוא אליהו' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9036 WHERE id = 'c50b76b2-5771-46cf-8f83-6172d3ed292a' AND sort_order = 36;  -- park 'מקבץ שאלות על מלכים ב''' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9037 WHERE id = '88768169-77c1-4595-8e2d-339c96c8f03d' AND sort_order = 37;  -- park 'כלי המקדש בתקופת אחשוורוש' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9038 WHERE id = '7179aa22-cde1-43a3-9c10-dc15aa3f8634' AND sort_order = 38;  -- park 'מעגל הקסמים בספר שופטים' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9039 WHERE id = '934f2715-1854-4d96-b869-4e11489f07ed' AND sort_order = 39;  -- park 'מלחמת בני אפרים ביפתח' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9040 WHERE id = '3e553e3b-34d7-471c-b2ff-4ccb6099df97' AND sort_order = 40;  -- park 'מלחמת פלשתים בגלבוע' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9041 WHERE id = '517acde1-1c67-496f-a286-99792cbd68f0' AND sort_order = 41;  -- park 'מלכות איש בשת' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9042 WHERE id = '0c7b50c8-a16d-4edf-9216-d5b6542c90ba' AND sort_order = 42;  -- park 'תגובות שונות של דוד המלך למות בניו' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9043 WHERE id = 'ecd3f79f-e901-4189-b453-b175eb15a1a3' AND sort_order = 43;  -- park 'המשך בירור בעניין מרד אבשלום' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9044 WHERE id = 'b5136e96-7cb3-4683-b5d5-c22afc23992e' AND sort_order = 44;  -- park 'רצח משפחתו של דוד בידי מואב' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9045 WHERE id = '8b14904d-710e-4bc6-9062-475a06f7a0cb' AND sort_order = 45;  -- park 'נישואי דוד המלך ורצפה בת איה' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9046 WHERE id = 'c162936e-473f-4218-b2f1-83e02e39536f' AND sort_order = 46;  -- park 'חזרת בת שבע לאוריה' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9047 WHERE id = 'c418408d-9140-49e4-90d1-3a36d2f77286' AND sort_order = 47;  -- park 'האם דוד היה נביא' (not on the old rav page (double-apply dup / deliberate addition) — parked)

-- verification: in-band ladder size (expect 31; old rows 31 minus 0 yoav minus 0 sanctioned-missing)
SELECT count(*) AS v_d68b38ad_inband FROM rabbi_page_items WHERE rabbi_id = 'd68b38ad-fd70-47d3-b667-20f68af6d8c4' AND sort_order < 9000;
-- verification: parked rows (expect 16)
SELECT count(*) AS v_d68b38ad_parked FROM rabbi_page_items WHERE rabbi_id = 'd68b38ad-fd70-47d3-b667-20f68af6d8c4' AND sort_order >= 9000;
-- verification: no in-band slot collisions (expect 0)
SELECT count(*) AS v_d68b38ad_collisions FROM (SELECT sort_order FROM rabbi_page_items WHERE rabbi_id='d68b38ad-fd70-47d3-b667-20f68af6d8c4' AND sort_order<9000 GROUP BY sort_order HAVING count(*)>1) q;

-- ============================================================================
-- §הרב יוסף שילר  (rabbi_id 2754844c-8149-4c50-922a-331664b4124e)
--   old rows: 16 · live rpi: 26 · pairs: 12 · inserts: 4 · parks: 14 · yoav: 0 · sanctioned-missing: 0
-- ----------------------------------------------------------------------------
UPDATE rabbi_page_items SET sort_order = 2 WHERE id = '7364cccd-7d1e-4b76-88be-44a077edc16c' AND sort_order <> 2;  -- old #1 'עולמות חדשים בפרשה'
UPDATE rabbi_page_items SET sort_order = 6 WHERE id = '90106a4c-92fe-4ee5-8a87-1a0ce02f3cd2' AND sort_order <> 6;  -- old #5 'בית חשמונאי ובית דוד'
UPDATE rabbi_page_items SET sort_order = 7 WHERE id = 'ad223c06-ce7f-492f-98a6-fa637edcdfb9' AND sort_order <> 7;  -- old #6 'הביטויים ''עם ישראל'' ''בני ישראל'' ו''עדת ישראל'''
UPDATE rabbi_page_items SET sort_order = 8 WHERE id = 'f8e08ba9-fedb-46e1-a5b0-cc7f6ec3945f' AND sort_order <> 8;  -- old #7 'בחירתו החופשית של עשו'
UPDATE rabbi_page_items SET sort_order = 9 WHERE id = '569a8866-ea9f-4d97-b176-2940c9ee87cd' AND sort_order <> 9;  -- old #8 'מעמד הגורל על חלוקת הנחלות'
UPDATE rabbi_page_items SET sort_order = 10 WHERE id = '045c7334-8578-4bb7-bbaa-ddaecc9af5af' AND sort_order <> 10;  -- old #9 'האם שאול ידע מיהו שמואל לפני שנפגשו?'
UPDATE rabbi_page_items SET sort_order = 11 WHERE id = '7f2b7dab-6090-41af-9283-c51980cfa0a4' AND sort_order <> 11;  -- old #10 'תגובת דוד למרידות בו'
UPDATE rabbi_page_items SET sort_order = 12 WHERE id = 'e13470dd-3134-4f9b-b7be-c10d1dbd64ec' AND sort_order <> 12;  -- old #11 'ברזילי הגלעדי בעיני חז"ל'
UPDATE rabbi_page_items SET sort_order = 13 WHERE id = 'c11c2213-fb60-4e6c-8efc-28b7f9887498' AND sort_order <> 13;  -- old #12 'מרד אדוניהו'
UPDATE rabbi_page_items SET sort_order = 14 WHERE id = 'db90a01c-baaf-42d6-a922-9583e1560497' AND sort_order <> 14;  -- old #13 'התהליך המיוחד של ימי ירבעם השני'
UPDATE rabbi_page_items SET sort_order = 15 WHERE id = 'b08b1fec-3cd2-4a43-a088-8eb8ce7cabe0' AND sort_order <> 15;  -- old #14 'גילו של אחזיה מלך יהודה'
UPDATE rabbi_page_items SET sort_order = 16 WHERE id = '196ffdba-0f13-4711-9c8e-fefeb2e519bd' AND sort_order <> 16;  -- old #15 'מדוע מרדכי מצוה על אסתר להכנס אל אחשורוש מיד?'

-- old row #0 'עולמות חדשים בפרשה'
INSERT INTO rabbi_page_items (rabbi_id, kind, series_id, sort_order)
SELECT '2754844c-8149-4c50-922a-331664b4124e', 'series', 'b66e0cdb-3953-4aa9-b8f7-e0fe27935167', 1
WHERE NOT EXISTS (SELECT 1 FROM rabbi_page_items WHERE rabbi_id='2754844c-8149-4c50-922a-331664b4124e' AND series_id='b66e0cdb-3953-4aa9-b8f7-e0fe27935167' AND sort_order=1);

-- old row #2 'עולמות חדשים בפרשה'
INSERT INTO rabbi_page_items (rabbi_id, kind, series_id, sort_order)
SELECT '2754844c-8149-4c50-922a-331664b4124e', 'series', '13854323-40c4-4434-9801-7d4c12694ca3', 3
WHERE NOT EXISTS (SELECT 1 FROM rabbi_page_items WHERE rabbi_id='2754844c-8149-4c50-922a-331664b4124e' AND series_id='13854323-40c4-4434-9801-7d4c12694ca3' AND sort_order=3);

-- old row #3 'עולמות חדשים בפרשה'
INSERT INTO rabbi_page_items (rabbi_id, kind, series_id, sort_order)
SELECT '2754844c-8149-4c50-922a-331664b4124e', 'series', '0b185ef9-32d7-4fd5-9446-15376d08aa62', 4
WHERE NOT EXISTS (SELECT 1 FROM rabbi_page_items WHERE rabbi_id='2754844c-8149-4c50-922a-331664b4124e' AND series_id='0b185ef9-32d7-4fd5-9446-15376d08aa62' AND sort_order=4);

-- old row #4 'עולמות חדשים בפרשה'
INSERT INTO rabbi_page_items (rabbi_id, kind, series_id, sort_order)
SELECT '2754844c-8149-4c50-922a-331664b4124e', 'series', '5267cccb-6b8a-49e4-ad22-49c2f1951b32', 5
WHERE NOT EXISTS (SELECT 1 FROM rabbi_page_items WHERE rabbi_id='2754844c-8149-4c50-922a-331664b4124e' AND series_id='5267cccb-6b8a-49e4-ad22-49c2f1951b32' AND sort_order=5);

UPDATE rabbi_page_items SET sort_order = 9046 WHERE id = '1c9d6566-2adf-4818-9b98-ac902edef10e' AND sort_order = 13;  -- park 'פוקד עוון אבות על בנים' (cross-attributed שו"ת — sanctioned rabbis_plan slot)
UPDATE rabbi_page_items SET sort_order = 9110 WHERE id = '5517a19a-01fc-4532-a6a9-83aa5d674d80' AND sort_order = 14;  -- park 'בקשת גדעון לאותות' (cross-attributed שו"ת — sanctioned rabbis_plan slot)
UPDATE rabbi_page_items SET sort_order = 9137 WHERE id = 'cd228576-9d04-44bd-80c5-79b2dfacf8d3' AND sort_order = 15;  -- park 'האם זרובל הוא נחמיה?' (cross-attributed שו"ת — sanctioned rabbis_plan slot)
UPDATE rabbi_page_items SET sort_order = 9139 WHERE id = '5245252e-e3dc-44f4-bd96-bd03b0d71ef6' AND sort_order = 16;  -- park 'חסרון ה''אורים ותומים'' בבית שני' (cross-attributed שו"ת — sanctioned rabbis_plan slot)
UPDATE rabbi_page_items SET sort_order = 9140 WHERE id = '38b2fcc2-a725-4364-83f9-eb75bb81c88a' AND sort_order = 17;  -- park 'עונשם של דור המדבר' (cross-attributed שו"ת — sanctioned rabbis_plan slot)
UPDATE rabbi_page_items SET sort_order = 9018 WHERE id = 'ccd3427e-b24e-4727-b4b9-5d42ef75828d' AND sort_order = 18;  -- park 'הנבואה הקדומה על החרבת האומות בידי סנחריב' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9019 WHERE id = '694b3db5-5e54-4a52-b451-1a16d7abd628' AND sort_order = 19;  -- park 'מעמד הגורל על חלוקת הנחלות' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9020 WHERE id = '3e710be5-026e-476e-ae5d-d3ba5acaf99c' AND sort_order = 20;  -- park 'מרד אדוניהו' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9021 WHERE id = '40f720a4-0734-4db4-b89f-01d80399c244' AND sort_order = 21;  -- park 'התהליך המיוחד של ימי ירבעם השני' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9022 WHERE id = '8a75d144-2901-414a-8e92-a4110ac6a51d' AND sort_order = 22;  -- park 'גילו של אחזיה מלך יהודה' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9023 WHERE id = '43370b07-12e0-4e11-9744-68396eb1ee2d' AND sort_order = 23;  -- park 'בקשת גדעון לאותות' (cross-attributed שו"ת — sanctioned rabbis_plan slot)
UPDATE rabbi_page_items SET sort_order = 9024 WHERE id = 'ce444f34-b75b-4f8a-bd32-c43293358cd9' AND sort_order = 24;  -- park 'האם שאול ידע מיהו שמואל לפני שנפגשו?' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9025 WHERE id = 'b24088c0-174c-4b78-82ec-aec3f7592cb8' AND sort_order = 25;  -- park 'תגובת דוד למרידות בו' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9026 WHERE id = 'd45ea872-0f2f-41c9-97ba-983729a4c325' AND sort_order = 26;  -- park 'ברזילי הגלעדי בעיני חז"ל' (not on the old rav page (double-apply dup / deliberate addition) — parked)

-- verification: in-band ladder size (expect 16; old rows 16 minus 0 yoav minus 0 sanctioned-missing)
SELECT count(*) AS v_2754844c_inband FROM rabbi_page_items WHERE rabbi_id = '2754844c-8149-4c50-922a-331664b4124e' AND sort_order < 9000;
-- verification: parked rows (expect 14)
SELECT count(*) AS v_2754844c_parked FROM rabbi_page_items WHERE rabbi_id = '2754844c-8149-4c50-922a-331664b4124e' AND sort_order >= 9000;
-- verification: no in-band slot collisions (expect 0)
SELECT count(*) AS v_2754844c_collisions FROM (SELECT sort_order FROM rabbi_page_items WHERE rabbi_id='2754844c-8149-4c50-922a-331664b4124e' AND sort_order<9000 GROUP BY sort_order HAVING count(*)>1) q;

-- ============================================================================
-- §הרב מאיר הילביץ'  (rabbi_id 71aa933c-5548-4ea7-8be0-dfb659202660)
--   old rows: 5 · live rpi: 6 · pairs: 5 · inserts: 0 · parks: 1 · yoav: 0 · sanctioned-missing: 0
-- ----------------------------------------------------------------------------
UPDATE rabbi_page_items SET sort_order = 9006 WHERE id = '9038947f-a048-491f-9102-d9989ffd9776' AND sort_order = 6;  -- park '''דניאל הרב מאיר הילביץ' (not on the old rav page (double-apply dup / deliberate addition) — parked)

-- verification: in-band ladder size (expect 5; old rows 5 minus 0 yoav minus 0 sanctioned-missing)
SELECT count(*) AS v_71aa933c_inband FROM rabbi_page_items WHERE rabbi_id = '71aa933c-5548-4ea7-8be0-dfb659202660' AND sort_order < 9000;
-- verification: parked rows (expect 1)
SELECT count(*) AS v_71aa933c_parked FROM rabbi_page_items WHERE rabbi_id = '71aa933c-5548-4ea7-8be0-dfb659202660' AND sort_order >= 9000;
-- verification: no in-band slot collisions (expect 0)
SELECT count(*) AS v_71aa933c_collisions FROM (SELECT sort_order FROM rabbi_page_items WHERE rabbi_id='71aa933c-5548-4ea7-8be0-dfb659202660' AND sort_order<9000 GROUP BY sort_order HAVING count(*)>1) q;

-- ============================================================================
-- §הרב מנחם שחור  (rabbi_id 4822f2bb-9d1c-4adc-9554-d2a2db7bdbc8)
--   old rows: 71 · live rpi: 88 · pairs: 69 · inserts: 0 · parks: 19 · yoav: 0 · sanctioned-missing: 2
-- ----------------------------------------------------------------------------
UPDATE rabbi_page_items SET sort_order = 44 WHERE id = '8c3fb4a0-dd90-4627-a7fe-6c87923cf331' AND sort_order <> 44;  -- old #43 'מדוע דרש ה'' מפרעה להוציא את ישראל לשלושה ימים בל'
UPDATE rabbi_page_items SET sort_order = 45 WHERE id = 'd0350934-279e-4d02-b1d7-43622c2aadee' AND sort_order <> 45;  -- old #44 'זמן השיעבוד'
UPDATE rabbi_page_items SET sort_order = 46 WHERE id = '84de1fc0-2064-430c-9607-22e7ccd8d429' AND sort_order <> 46;  -- old #45 'מתי נזכרות הנהגות ומידות טובות של הנביאים בכתוב'
UPDATE rabbi_page_items SET sort_order = 48 WHERE id = '4fb9e9a6-2b6f-40f4-b1e7-4f491639f791' AND sort_order <> 48;  -- old #47 'מדוע יש צורך בבדים לכלי המקדש הקבועים במקומם?'
UPDATE rabbi_page_items SET sort_order = 49 WHERE id = '7b77ca0c-5256-447d-8118-b0c9b4b3a36e' AND sort_order <> 49;  -- old #48 'מלך יריחו והמרגלים שבאו לרחב'
UPDATE rabbi_page_items SET sort_order = 50 WHERE id = '11953189-0278-4136-96a3-52a2080aec48' AND sort_order <> 50;  -- old #49 'שירה במעבר הירדן'
UPDATE rabbi_page_items SET sort_order = 51 WHERE id = '785b15f1-b54e-4ab8-80cb-1931c1e378ed' AND sort_order <> 51;  -- old #50 'האם בתקופת השופטים חלה התקדמות?'
UPDATE rabbi_page_items SET sort_order = 52 WHERE id = 'b62b57c6-8385-4460-8b32-55c9147e7ba2' AND sort_order <> 52;  -- old #51 'בני רחל בספר שופטים'
UPDATE rabbi_page_items SET sort_order = 53 WHERE id = 'ac25ad58-c133-4ecb-9d63-da3c0db045fb' AND sort_order <> 53;  -- old #52 'כיבוש העיר לוז'
UPDATE rabbi_page_items SET sort_order = 54 WHERE id = 'a66be683-8f49-46a0-a9b0-8e44f6331041' AND sort_order <> 54;  -- old #53 'למה חמל שאול על אגג?'
UPDATE rabbi_page_items SET sort_order = 55 WHERE id = '83fa1b0f-56e9-4427-9b3d-65f3ed25ce45' AND sort_order <> 55;  -- old #54 'האם שאול היה אמור לזכות למלכות נצחית?'
UPDATE rabbi_page_items SET sort_order = 56 WHERE id = 'c11f4d11-396d-41d0-a034-ac0a627de356' AND sort_order <> 56;  -- old #55 'שאול ודוד'
UPDATE rabbi_page_items SET sort_order = 57 WHERE id = '17ac8083-893d-4352-a984-7b87146aed83' AND sort_order <> 57;  -- old #56 'מדוע דוד פקד את ישראל?'
UPDATE rabbi_page_items SET sort_order = 58 WHERE id = 'bc380f40-5a95-4790-ab8d-c5d04406eebf' AND sort_order <> 58;  -- old #57 'דוד ובת שבע'
UPDATE rabbi_page_items SET sort_order = 59 WHERE id = 'ee7762cc-4143-4f07-96ba-2cb04becc91e' AND sort_order <> 59;  -- old #58 'אמנון ותמר'
UPDATE rabbi_page_items SET sort_order = 60 WHERE id = '5cbc0782-dc34-4ad3-aa08-5b6f43c2f952' AND sort_order <> 60;  -- old #59 'האם חטא איש האלוקים מיהודה?'
UPDATE rabbi_page_items SET sort_order = 61 WHERE id = '4e2f1d0e-54f7-4b42-bb2c-079b1c6f8492' AND sort_order <> 61;  -- old #60 'שיתוף הפעולה של יהושפט עם משפחת אחאב'
UPDATE rabbi_page_items SET sort_order = 62 WHERE id = 'b7534c3e-b28f-486f-8c57-fed29c60e183' AND sort_order <> 62;  -- old #61 'בית ד'' ובית המלך'
UPDATE rabbi_page_items SET sort_order = 63 WHERE id = '355c4b54-6229-4994-8449-fcac79898d2c' AND sort_order <> 63;  -- old #62 'בן האישה הצרפתית'
UPDATE rabbi_page_items SET sort_order = 64 WHERE id = '2747c81e-7a3b-40a2-ab33-1ad053b89089' AND sort_order <> 64;  -- old #63 'יונה - חסד או אמת'
UPDATE rabbi_page_items SET sort_order = 65 WHERE id = '0d8656b5-2991-44c8-8422-3f1d721b910b' AND sort_order <> 65;  -- old #64 'גילו של אחז'
UPDATE rabbi_page_items SET sort_order = 66 WHERE id = '6f7494f5-b6e6-40e0-9449-21336bcdf35a' AND sort_order <> 66;  -- old #65 'על איזו תקופה מדברות נבואות הנביאים האחרונים?'
UPDATE rabbi_page_items SET sort_order = 67 WHERE id = 'ce9ff9bc-4fe6-4e82-8a7d-2c0994537701' AND sort_order <> 67;  -- old #66 'נבואות חורבן בימי חזקיה?'
UPDATE rabbi_page_items SET sort_order = 68 WHERE id = '00e56ab1-1485-4d2b-97a9-3d00cf771866' AND sort_order <> 68;  -- old #67 'קץ 70 שנה ובניית בית שני'
UPDATE rabbi_page_items SET sort_order = 69 WHERE id = 'cedf595b-d096-4f54-a979-6af999350b7b' AND sort_order <> 69;  -- old #68 'תפקידו של ספר דברי הימים'
UPDATE rabbi_page_items SET sort_order = 70 WHERE id = '2da96356-fa56-4b26-9e2e-49ae6c640d53' AND sort_order <> 70;  -- old #69 'עין הארץ'
UPDATE rabbi_page_items SET sort_order = 71 WHERE id = '5b239ee9-eb21-41be-bb54-a56003232a20' AND sort_order <> 71;  -- old #70 'קורבנות מוספים והכניסה לארץ'

UPDATE rabbi_page_items SET sort_order = 9070 WHERE id = 'cb482915-48cd-4603-ba1c-207527d50eb0' AND sort_order = 70;  -- park 'על איזו תקופה מדברות נבואות הנביאים האחרונים?' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9071 WHERE id = 'b5946a48-0167-416d-a096-be10940abed1' AND sort_order = 71;  -- park 'מלך יריחו והמרגלים שבאו לרחב' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9072 WHERE id = '50209f20-5fe7-4eb3-a6f8-2934c9c00cbc' AND sort_order = 72;  -- park 'נבואות חורבן בימי חזקיה?' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9073 WHERE id = '9735e4de-bf51-41e1-9180-e5ffc117e7cf' AND sort_order = 73;  -- park 'שירה במעבר הירדן' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9074 WHERE id = '159c6f7f-4c19-4b4d-9426-d1f62f9e2fb2' AND sort_order = 74;  -- park 'האם חטא איש האלוקים מיהודה?' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9075 WHERE id = '4d929f08-0554-4270-a60d-0a7d38cd997a' AND sort_order = 75;  -- park 'שיתוף הפעולה של יהושפט עם משפחת אחאב' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9076 WHERE id = 'd09560f9-0bcc-46dd-ae22-20445b189c22' AND sort_order = 76;  -- park 'בית ד'' ובית המלך' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9077 WHERE id = '57a409ee-5ab8-436a-8216-67bc0c11762c' AND sort_order = 77;  -- park 'בן האישה הצרפתית' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9078 WHERE id = 'ad2dfd6d-961a-4486-82c9-2a035c9c243f' AND sort_order = 78;  -- park 'יונה - חסד או אמת' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9079 WHERE id = 'f7d820f8-e629-4a4f-ba84-adb3d98f4325' AND sort_order = 79;  -- park 'גילו של אחז' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9080 WHERE id = '051cf574-a50b-4430-b9dd-c807fd7f7b04' AND sort_order = 80;  -- park 'האם בתקופת השופטים חלה התקדמות?' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9081 WHERE id = 'a57cb9ef-1df6-4419-aa2d-775f7b605267' AND sort_order = 81;  -- park 'בני רחל בספר שופטים' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9082 WHERE id = '76ae1459-73e9-416b-93b7-69028f3ad3d6' AND sort_order = 82;  -- park 'כיבוש העיר לוז' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9083 WHERE id = '6900d673-759f-4940-b20e-e570f4cdca73' AND sort_order = 83;  -- park 'למה חמל שאול על אגג?' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9084 WHERE id = '569dcf0d-8e9f-4629-8f0d-3fbe27d59ad6' AND sort_order = 84;  -- park 'האם שאול היה אמור לזכות למלכות נצחית?' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9085 WHERE id = 'c50ce2a5-a32d-478b-97d4-1efe4f16fedd' AND sort_order = 85;  -- park 'שאול ודוד' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9086 WHERE id = '1ee8814e-70af-4a05-b0af-ccaec35e709f' AND sort_order = 86;  -- park 'מדוע דוד פקד את ישראל?' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9087 WHERE id = '9673595c-1b6f-41dd-863f-a16183f8f384' AND sort_order = 87;  -- park 'דוד ובת שבע' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9088 WHERE id = '591bdf33-8399-4613-9f23-0e550692e0ef' AND sort_order = 88;  -- park 'אמנון ותמר' (not on the old rav page (double-apply dup / deliberate addition) — parked)

-- verification: in-band ladder size (expect 69; old rows 71 minus 0 yoav minus 2 sanctioned-missing)
SELECT count(*) AS v_4822f2bb_inband FROM rabbi_page_items WHERE rabbi_id = '4822f2bb-9d1c-4adc-9554-d2a2db7bdbc8' AND sort_order < 9000;
-- verification: parked rows (expect 19)
SELECT count(*) AS v_4822f2bb_parked FROM rabbi_page_items WHERE rabbi_id = '4822f2bb-9d1c-4adc-9554-d2a2db7bdbc8' AND sort_order >= 9000;
-- verification: no in-band slot collisions (expect 0)
SELECT count(*) AS v_4822f2bb_collisions FROM (SELECT sort_order FROM rabbi_page_items WHERE rabbi_id='4822f2bb-9d1c-4adc-9554-d2a2db7bdbc8' AND sort_order<9000 GROUP BY sort_order HAVING count(*)>1) q;

-- ============================================================================
-- §הרב נועם וידר  (rabbi_id ff233638-a99c-4049-9613-41d44a12f90a)
--   old rows: 1 · live rpi: 15 · pairs: 1 · inserts: 0 · parks: 14 · yoav: 0 · sanctioned-missing: 0
-- ----------------------------------------------------------------------------
UPDATE rabbi_page_items SET sort_order = 9002 WHERE id = 'cbb4d867-744b-4ef7-8635-3cfa90d67548' AND sort_order = 2;  -- park 'ירמיהו - נביא לכל העמים' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9003 WHERE id = 'abc93e90-0dde-45f7-8bc1-1ccfb7641836' AND sort_order = 3;  -- park 'פתיחת פיו של יחזקאל' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9004 WHERE id = '27de7937-1d93-4528-a8fa-b6e257dec3a8' AND sort_order = 4;  -- park 'ההבדל בין יהושע לשופטים' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9005 WHERE id = '53e8d89f-b8d1-4362-979c-1f94ca019112' AND sort_order = 5;  -- park 'כריתת ברית עם יושב הארץ' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9006 WHERE id = '31459e8c-7223-40f0-9ccd-59a5ce0c6e6c' AND sort_order = 6;  -- park 'מדוע הקב"ה לא הקים מנהיג לאחר מות יהושע?' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9007 WHERE id = 'f3c3651d-b2d0-4cbc-8f7d-c8c152a81145' AND sort_order = 7;  -- park 'מדוע רץ אליהו לפני אחאב' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9008 WHERE id = 'a9b10498-cfbf-4793-9a48-01c3a4cde25f' AND sort_order = 8;  -- park 'חטאו ועונשו של גיחזי' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9009 WHERE id = 'cca85b4e-cfa1-4700-a4c3-2c686bf975b2' AND sort_order = 9;  -- park 'השופטים ה"קטנים"' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9010 WHERE id = '000502ae-0a1c-4b7b-8902-a48084bf2de7' AND sort_order = 10;  -- park 'יאיר בן מנשה מחומש במדבר ויאיר הגלעדי מספר שופטי' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9011 WHERE id = '3fe660ee-f88e-479f-bf67-f39569886468' AND sort_order = 11;  -- park 'כיבושי בני ישראל לאחר מות יהושע' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9012 WHERE id = '66e15882-88e0-468e-8f31-e9258a5c444a' AND sort_order = 12;  -- park 'הריגת כוהני נוב' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9013 WHERE id = '462c722d-0ba7-4aa5-a5d4-987e23d91e4d' AND sort_order = 13;  -- park 'בן שנה שאול במלכו - האמנם?' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9014 WHERE id = '24efa1b7-363d-4352-bf63-7e3a99a89425' AND sort_order = 14;  -- park 'הבטחת שאול את ביתו למכה גלית' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9015 WHERE id = '89c1dd5b-1473-46bb-b41f-97098dce930d' AND sort_order = 15;  -- park 'מי היו הכרתי והפלתי?' (not on the old rav page (double-apply dup / deliberate addition) — parked)

-- verification: in-band ladder size (expect 1; old rows 1 minus 0 yoav minus 0 sanctioned-missing)
SELECT count(*) AS v_ff233638_inband FROM rabbi_page_items WHERE rabbi_id = 'ff233638-a99c-4049-9613-41d44a12f90a' AND sort_order < 9000;
-- verification: parked rows (expect 14)
SELECT count(*) AS v_ff233638_parked FROM rabbi_page_items WHERE rabbi_id = 'ff233638-a99c-4049-9613-41d44a12f90a' AND sort_order >= 9000;
-- verification: no in-band slot collisions (expect 0)
SELECT count(*) AS v_ff233638_collisions FROM (SELECT sort_order FROM rabbi_page_items WHERE rabbi_id='ff233638-a99c-4049-9613-41d44a12f90a' AND sort_order<9000 GROUP BY sort_order HAVING count(*)>1) q;

-- ============================================================================
-- §הרב נחום נריה  (rabbi_id b1010001-0001-4000-8000-000000000014)
--   old rows: 1 · live rpi: 0 · pairs: 0 · inserts: 1 · parks: 0 · yoav: 0 · sanctioned-missing: 0
-- ----------------------------------------------------------------------------
-- old row #0 'מהפכות הפסח בתנ"ך'
INSERT INTO rabbi_page_items (rabbi_id, kind, lesson_id, sort_order)
SELECT 'b1010001-0001-4000-8000-000000000014', 'lesson', 'e96d96aa-364d-4cd3-b2d8-ec0b5becdbe6', 1
WHERE NOT EXISTS (SELECT 1 FROM rabbi_page_items WHERE rabbi_id='b1010001-0001-4000-8000-000000000014' AND lesson_id='e96d96aa-364d-4cd3-b2d8-ec0b5becdbe6' AND sort_order=1);

-- verification: in-band ladder size (expect 1; old rows 1 minus 0 yoav minus 0 sanctioned-missing)
SELECT count(*) AS v_b1010001_inband FROM rabbi_page_items WHERE rabbi_id = 'b1010001-0001-4000-8000-000000000014' AND sort_order < 9000;
-- verification: parked rows (expect 0)
SELECT count(*) AS v_b1010001_parked FROM rabbi_page_items WHERE rabbi_id = 'b1010001-0001-4000-8000-000000000014' AND sort_order >= 9000;
-- verification: no in-band slot collisions (expect 0)
SELECT count(*) AS v_b1010001_collisions FROM (SELECT sort_order FROM rabbi_page_items WHERE rabbi_id='b1010001-0001-4000-8000-000000000014' AND sort_order<9000 GROUP BY sort_order HAVING count(*)>1) q;

-- ============================================================================
-- §הרב עמירם אלבה  (rabbi_id 3da1df9d-4ed5-48ba-9ffa-e3c5271d40e1)
--   old rows: 19 · live rpi: 20 · pairs: 19 · inserts: 0 · parks: 1 · yoav: 0 · sanctioned-missing: 0
-- ----------------------------------------------------------------------------
UPDATE rabbi_page_items SET sort_order = 9020 WHERE id = 'c090522d-dd29-4f81-a5f1-0ea0e92d90b0' AND sort_order = 20;  -- park 'איך ללמד ילדים על חשיבות התורה' (not on the old rav page (double-apply dup / deliberate addition) — parked)

-- verification: in-band ladder size (expect 19; old rows 19 minus 0 yoav minus 0 sanctioned-missing)
SELECT count(*) AS v_3da1df9d_inband FROM rabbi_page_items WHERE rabbi_id = '3da1df9d-4ed5-48ba-9ffa-e3c5271d40e1' AND sort_order < 9000;
-- verification: parked rows (expect 1)
SELECT count(*) AS v_3da1df9d_parked FROM rabbi_page_items WHERE rabbi_id = '3da1df9d-4ed5-48ba-9ffa-e3c5271d40e1' AND sort_order >= 9000;
-- verification: no in-band slot collisions (expect 0)
SELECT count(*) AS v_3da1df9d_collisions FROM (SELECT sort_order FROM rabbi_page_items WHERE rabbi_id='3da1df9d-4ed5-48ba-9ffa-e3c5271d40e1' AND sort_order<9000 GROUP BY sort_order HAVING count(*)>1) q;

-- ============================================================================
-- §הרב עמנואל בן ארצי  (rabbi_id 744da303-22be-4062-a822-4ba8e8f1b02d)
--   old rows: 48 · live rpi: 53 · pairs: 45 · inserts: 1 · parks: 8 · yoav: 2 · sanctioned-missing: 0
-- ----------------------------------------------------------------------------
UPDATE rabbi_page_items SET sort_order = 8 WHERE id = '23bfe85e-8e8b-4c60-a5a9-a57cfade82d1' AND sort_order <> 8;  -- old #7 'פשט בפרשה'
UPDATE rabbi_page_items SET sort_order = 12 WHERE id = '5befe7ac-d8a4-427e-9f9e-07dae053b173' AND sort_order <> 12;  -- old #11 'קורס דיגיטלי - מלכים'
UPDATE rabbi_page_items SET sort_order = 13 WHERE id = 'c0c55879-f7c9-4df1-afb9-f39d87ab919e' AND sort_order <> 13;  -- old #12 'לב הפרק'
UPDATE rabbi_page_items SET sort_order = 14 WHERE id = '07d15510-ed53-4cb8-8146-762316563381' AND sort_order <> 14;  -- old #13 'תנ"ך בעיון - ישעיהו'
UPDATE rabbi_page_items SET sort_order = 15 WHERE id = '2bfa4f08-f51a-4502-90e8-6ab6b3543171' AND sort_order <> 15;  -- old #14 'לב הפרק - ישעיהו'
UPDATE rabbi_page_items SET sort_order = 16 WHERE id = '3d630f9c-64c5-4f83-9673-2dbd30befd94' AND sort_order <> 16;  -- old #15 'חמאה ודבש - חגי'
UPDATE rabbi_page_items SET sort_order = 17 WHERE id = '177e5fba-4330-4251-89c2-a425f38a8fc9' AND sort_order <> 17;  -- old #16 'לב הפרק - חגי זכריה ומלאכי'
UPDATE rabbi_page_items SET sort_order = 18 WHERE id = '30c8268f-854c-4205-bc59-7bbdb79c795f' AND sort_order <> 18;  -- old #17 'פירוש על תהילים לפי גדולי ישראל'
UPDATE rabbi_page_items SET sort_order = 19 WHERE id = '721d8b0a-d24c-499d-af32-e5d8b0c61015' AND sort_order <> 19;  -- old #18 'ביאור ספר משלי'
UPDATE rabbi_page_items SET sort_order = 20 WHERE id = '229d7d31-fa72-472e-9722-6a366b6fa525' AND sort_order <> 20;  -- old #19 'חמאה ודבש - פירוש פשט על מגילת אסתר'
UPDATE rabbi_page_items SET sort_order = 21 WHERE id = '2ff31c40-970d-49fa-a2f6-5bab36e15a97' AND sort_order <> 21;  -- old #20 'תרגום לעברית של ספר דניאל'
UPDATE rabbi_page_items SET sort_order = 23 WHERE id = '56e2617a-3474-410e-826a-ab51063033ba' AND sort_order <> 23;  -- old #22 'תרגום לעברית של ספר עזרא'
UPDATE rabbi_page_items SET sort_order = 24 WHERE id = '1e19f8c3-5d39-4521-a66d-0e5406775cac' AND sort_order <> 24;  -- old #23 'לב הפרק - עזרא ונחמיה'
UPDATE rabbi_page_items SET sort_order = 25 WHERE id = '854d17c0-9197-4868-b3df-9f997b316cad' AND sort_order <> 25;  -- old #24 'לב הפרק - שופטים'
UPDATE rabbi_page_items SET sort_order = 27 WHERE id = '3225a96d-bc9b-4c3a-8df9-3dabe4cdc760' AND sort_order <> 27;  -- old #26 'מפת עזר לזיהוי אתרי התנ"ך בארץ ישראל'
UPDATE rabbi_page_items SET sort_order = 28 WHERE id = '7c94b140-8f45-464c-95ee-99932ff5be77' AND sort_order <> 28;  -- old #27 'ציר זמן יהושע שופטים'
UPDATE rabbi_page_items SET sort_order = 29 WHERE id = '7c0af92e-9bf5-44d8-8872-d1e766636da1' AND sort_order <> 29;  -- old #28 'ציר זמן גלות בבל'
UPDATE rabbi_page_items SET sort_order = 30 WHERE id = 'c6e60c9a-95b0-43bb-9cdd-156bfabb00f6' AND sort_order <> 30;  -- old #29 'ציר זמן שנה וחצי ראשונות במדבר'
UPDATE rabbi_page_items SET sort_order = 31 WHERE id = 'd5fb532b-758e-4209-98e2-9b4ef43e3866' AND sort_order <> 31;  -- old #30 'פירוש עצמאי של פסוקי התנ"ך'
UPDATE rabbi_page_items SET sort_order = 32 WHERE id = 'afce1231-3c0b-4663-900a-b5157243bb44' AND sort_order <> 32;  -- old #31 'תהלים עם פירוש פשט'
UPDATE rabbi_page_items SET sort_order = 33 WHERE id = '7173376d-802c-4de4-943a-89029040d7ef' AND sort_order <> 33;  -- old #32 'מגילת אסתר וספרי הבית השני 1'
UPDATE rabbi_page_items SET sort_order = 34 WHERE id = 'd6959dbd-709a-4b0e-9d3e-33a80365a298' AND sort_order <> 34;  -- old #33 'מגילת אסתר וספרי הבית השני 2'
UPDATE rabbi_page_items SET sort_order = 35 WHERE id = 'a96441c6-d0ee-4e91-8453-f885427ff1a9' AND sort_order <> 35;  -- old #34 'הסבר פשוט על מבנה ארץ ישראל'
UPDATE rabbi_page_items SET sort_order = 36 WHERE id = '14daed3c-5cd2-44d8-bb92-f221432304db' AND sort_order <> 36;  -- old #35 'על כן קראו לימים האלה פורים על שם הפור - למה הפו'
UPDATE rabbi_page_items SET sort_order = 37 WHERE id = '181fae58-b2e0-4536-9c20-462884e0a8ef' AND sort_order <> 37;  -- old #36 'מפת מקומות ונחלות בארץ ישראל'
UPDATE rabbi_page_items SET sort_order = 39 WHERE id = 'da462991-11c7-4693-9849-470aff1711b8' AND sort_order <> 39;  -- old #38 'הסבר פשוט על מבנה ארץ ישראל והנחלות'
UPDATE rabbi_page_items SET sort_order = 41 WHERE id = '32da8c17-7bd4-459e-9a7d-6507ac5e3562' AND sort_order <> 41;  -- old #40 'שרטוט בית המקדש ביחזקאל על פי שיטות המלבי"ם רש"י'
UPDATE rabbi_page_items SET sort_order = 43 WHERE id = '33169e49-1a30-4777-b45c-a11665924451' AND sort_order <> 43;  -- old #42 'חטא בני עלי - במבט כולל על הכהונה'
UPDATE rabbi_page_items SET sort_order = 44 WHERE id = '5a8ddd14-6230-4042-8583-ab8d458a225e' AND sort_order <> 44;  -- old #43 'למה שאול רודף את דוד'
UPDATE rabbi_page_items SET sort_order = 45 WHERE id = '463356f0-8011-45df-ac21-cf77e0893570' AND sort_order <> 45;  -- old #44 'מעשה דוד ובת שבע על פי הפשט'
UPDATE rabbi_page_items SET sort_order = 46 WHERE id = 'a037bbd1-4ed6-4a46-9d5b-8d88f00d31f4' AND sort_order <> 46;  -- old #45 'שרטוט בית המקדש ביחזקאל לפי שיטות המלבי"ם רש"י ו'
UPDATE rabbi_page_items SET sort_order = 47 WHERE id = 'b7ca8b68-c4c7-4af3-a42e-fa679db196bf' AND sort_order <> 47;  -- old #46 'מגילת אסתר וספרי הבית השני'
UPDATE rabbi_page_items SET sort_order = 48 WHERE id = 'b387d611-d9ef-4591-9841-987d3f308b07' AND sort_order <> 48;  -- old #47 'זיהוי בימינו של המקומות בתנ"ך'

-- old row #37 'ציר זמן יהושע שופטים'
INSERT INTO rabbi_page_items (rabbi_id, kind, lesson_id, sort_order)
SELECT '744da303-22be-4062-a822-4ba8e8f1b02d', 'lesson', '4586cc0a-4d85-5fda-b9bc-33daaee9e6fe', 38
WHERE NOT EXISTS (SELECT 1 FROM rabbi_page_items WHERE rabbi_id='744da303-22be-4062-a822-4ba8e8f1b02d' AND lesson_id='4586cc0a-4d85-5fda-b9bc-33daaee9e6fe' AND sort_order=38);

UPDATE rabbi_page_items SET sort_order = 9022 WHERE id = '0d22b0bc-843c-4123-9a72-026fa08e193f' AND sort_order = 22;  -- park 'ציר זמן יהושע שופטים' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9024 WHERE id = '8b14c914-759a-45ff-a7cd-904266b362ba' AND sort_order = 24;  -- park 'ציר זמן שנה וחצי ראשונות במדבר' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9042 WHERE id = 'f0f1da50-c62d-482b-b8df-eba4389b9140' AND sort_order = 40;  -- park 'למה כעס יעקב על רחל?' (cross-attributed שו"ת — sanctioned rabbis_plan slot)
UPDATE rabbi_page_items SET sort_order = 9131 WHERE id = '2e354a45-4c0f-4dac-a56a-f350c53a5c69' AND sort_order = 41;  -- park 'למה היתה רעידת אדמה בימי עוזיהו?' (cross-attributed שו"ת — sanctioned rabbis_plan slot)
UPDATE rabbi_page_items SET sort_order = 9043 WHERE id = '3146eb7a-0e66-4538-96fd-dbf5a7202895' AND sort_order = 42;  -- park 'למה היתה רעידת אדמה בימי עוזיהו?' (cross-attributed שו"ת — sanctioned rabbis_plan slot)
UPDATE rabbi_page_items SET sort_order = 9044 WHERE id = '3ee8c33f-8943-440c-a805-732425ae62a9' AND sort_order = 43;  -- park 'זיהוי בימינו של המקומות בתנ"ך' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9045 WHERE id = '2405ac0c-ff14-4bcb-ba12-63450e775cd6' AND sort_order = 44;  -- park 'יהודה וישראל - אז והיום' (not on the old rav page (double-apply dup / deliberate addition) — parked)
UPDATE rabbi_page_items SET sort_order = 9051 WHERE id = '161470ee-6d7a-440d-88e4-c1fb3728b39a' AND sort_order = 51;  -- park 'זיהוי בימינו של המקומות בתנ"ך' (not on the old rav page (double-apply dup / deliberate addition) — parked)

-- verification: in-band ladder size (expect 46; old rows 48 minus 2 yoav minus 0 sanctioned-missing)
SELECT count(*) AS v_744da303_inband FROM rabbi_page_items WHERE rabbi_id = '744da303-22be-4062-a822-4ba8e8f1b02d' AND sort_order < 9000;
-- verification: parked rows (expect 8)
SELECT count(*) AS v_744da303_parked FROM rabbi_page_items WHERE rabbi_id = '744da303-22be-4062-a822-4ba8e8f1b02d' AND sort_order >= 9000;
-- verification: no in-band slot collisions (expect 0)
SELECT count(*) AS v_744da303_collisions FROM (SELECT sort_order FROM rabbi_page_items WHERE rabbi_id='744da303-22be-4062-a822-4ba8e8f1b02d' AND sort_order<9000 GROUP BY sort_order HAVING count(*)>1) q;

-- ============================================================================
-- §הרב שלמה אבינר  (rabbi_id 277e3084-aaff-44e6-a83a-5facf893607e)
--   old rows: 11 · live rpi: 8 · pairs: 8 · inserts: 3 · parks: 0 · yoav: 0 · sanctioned-missing: 0
-- ----------------------------------------------------------------------------
UPDATE rabbi_page_items SET sort_order = 4 WHERE id = 'e77e7bde-1abc-4b58-8056-2a54ac374882' AND sort_order <> 4;  -- old #3 'הרב אבינר על פרשיות שמות'
UPDATE rabbi_page_items SET sort_order = 6 WHERE id = 'f102ff38-1321-42d8-a1e5-49717e684c60' AND sort_order <> 6;  -- old #5 'הרב אבינר על פרשיות ויקרא'
UPDATE rabbi_page_items SET sort_order = 7 WHERE id = '5e106a80-f5a8-4a13-9d1e-3f30c11450c7' AND sort_order <> 7;  -- old #6 'הרב אבינר שיחות על פרשיות ויקרא'
UPDATE rabbi_page_items SET sort_order = 8 WHERE id = 'de52e247-6a00-4ccb-a264-c0513acc8a4c' AND sort_order <> 8;  -- old #7 'הרב אבינר על פרשיות במדבר'
UPDATE rabbi_page_items SET sort_order = 10 WHERE id = '92b76bef-5ae1-45d4-9b7e-7766bf7e97f7' AND sort_order <> 10;  -- old #9 'הרב אבינר על פרשיות דברים'
UPDATE rabbi_page_items SET sort_order = 11 WHERE id = '956d6662-06ac-4c62-912f-ed107fb2251c' AND sort_order <> 11;  -- old #10 'הרב אבינר שיחות על פרשיות דברים'

-- old row #2 'הרב שלמה אבינר על פרשיות בראשית'
INSERT INTO rabbi_page_items (rabbi_id, kind, series_id, sort_order)
SELECT '277e3084-aaff-44e6-a83a-5facf893607e', 'series', 'b2e079cd-15cf-4172-ab57-60b362f8e74c', 3
WHERE NOT EXISTS (SELECT 1 FROM rabbi_page_items WHERE rabbi_id='277e3084-aaff-44e6-a83a-5facf893607e' AND series_id='b2e079cd-15cf-4172-ab57-60b362f8e74c' AND sort_order=3);

-- old row #4 'הרב אבינר על פרשיות שמות'
INSERT INTO rabbi_page_items (rabbi_id, kind, series_id, sort_order)
SELECT '277e3084-aaff-44e6-a83a-5facf893607e', 'series', '1f4cf5c3-8435-456e-bc08-17d05c8d7535', 5
WHERE NOT EXISTS (SELECT 1 FROM rabbi_page_items WHERE rabbi_id='277e3084-aaff-44e6-a83a-5facf893607e' AND series_id='1f4cf5c3-8435-456e-bc08-17d05c8d7535' AND sort_order=5);

-- old row #8 'הרב שלמה אבינר על פרשיות במדבר'
INSERT INTO rabbi_page_items (rabbi_id, kind, series_id, sort_order)
SELECT '277e3084-aaff-44e6-a83a-5facf893607e', 'series', 'd860d934-c76d-47d7-a988-5fe21358b3bd', 9
WHERE NOT EXISTS (SELECT 1 FROM rabbi_page_items WHERE rabbi_id='277e3084-aaff-44e6-a83a-5facf893607e' AND series_id='d860d934-c76d-47d7-a988-5fe21358b3bd' AND sort_order=9);

-- verification: in-band ladder size (expect 11; old rows 11 minus 0 yoav minus 0 sanctioned-missing)
SELECT count(*) AS v_277e3084_inband FROM rabbi_page_items WHERE rabbi_id = '277e3084-aaff-44e6-a83a-5facf893607e' AND sort_order < 9000;
-- verification: parked rows (expect 0)
SELECT count(*) AS v_277e3084_parked FROM rabbi_page_items WHERE rabbi_id = '277e3084-aaff-44e6-a83a-5facf893607e' AND sort_order >= 9000;
-- verification: no in-band slot collisions (expect 0)
SELECT count(*) AS v_277e3084_collisions FROM (SELECT sort_order FROM rabbi_page_items WHERE rabbi_id='277e3084-aaff-44e6-a83a-5facf893607e' AND sort_order<9000 GROUP BY sort_order HAVING count(*)>1) q;

-- ============================================================================
-- §הרבנית בת שבע יוסיפון (לנשים)  (rabbi_id bc6e5c0b-2465-4ed1-9de6-1fc28250c387)
--   old rows: 1 · live rpi: 0 · pairs: 0 · inserts: 1 · parks: 0 · yoav: 0 · sanctioned-missing: 0
-- ----------------------------------------------------------------------------
-- old row #0 'רוצה להיות מלכה'
INSERT INTO rabbi_page_items (rabbi_id, kind, lesson_id, sort_order)
SELECT 'bc6e5c0b-2465-4ed1-9de6-1fc28250c387', 'lesson', '496a7521-0b1e-419a-972d-fa3b97b85f96', 1
WHERE NOT EXISTS (SELECT 1 FROM rabbi_page_items WHERE rabbi_id='bc6e5c0b-2465-4ed1-9de6-1fc28250c387' AND lesson_id='496a7521-0b1e-419a-972d-fa3b97b85f96' AND sort_order=1);

-- verification: in-band ladder size (expect 1; old rows 1 minus 0 yoav minus 0 sanctioned-missing)
SELECT count(*) AS v_bc6e5c0b_inband FROM rabbi_page_items WHERE rabbi_id = 'bc6e5c0b-2465-4ed1-9de6-1fc28250c387' AND sort_order < 9000;
-- verification: parked rows (expect 0)
SELECT count(*) AS v_bc6e5c0b_parked FROM rabbi_page_items WHERE rabbi_id = 'bc6e5c0b-2465-4ed1-9de6-1fc28250c387' AND sort_order >= 9000;
-- verification: no in-band slot collisions (expect 0)
SELECT count(*) AS v_bc6e5c0b_collisions FROM (SELECT sort_order FROM rabbi_page_items WHERE rabbi_id='bc6e5c0b-2465-4ed1-9de6-1fc28250c387' AND sort_order<9000 GROUP BY sort_order HAVING count(*)>1) q;

-- ============================================================================
-- §ושננתם  (rabbi_id e6c81665-5737-4c82-b96e-7527cc0e6ee6)
--   old rows: 40 · live rpi: 35 · pairs: 35 · inserts: 5 · parks: 0 · yoav: 0 · sanctioned-missing: 0
-- ----------------------------------------------------------------------------
-- retarget old row #14 to the legacy-url-exact lesson (basename collision in the plan match)
UPDATE rabbi_page_items SET lesson_id = 'e001f03e-8539-5533-8035-f8cf2035518b', sort_order = 15
WHERE id = '53baee28-e6d2-4994-80de-c1b4a78e7c4d' AND lesson_id = '3bfe8dad-ec4e-490c-9fb6-c5a65d5f9b21';

-- old row #6 'המספרים במקרא - מדויקים או מעוגלים?'
INSERT INTO rabbi_page_items (rabbi_id, kind, lesson_id, sort_order)
SELECT 'e6c81665-5737-4c82-b96e-7527cc0e6ee6', 'lesson', 'f8166389-c3db-4ad9-8037-20ae6fc61579', 7
WHERE NOT EXISTS (SELECT 1 FROM rabbi_page_items WHERE rabbi_id='e6c81665-5737-4c82-b96e-7527cc0e6ee6' AND lesson_id='f8166389-c3db-4ad9-8037-20ae6fc61579' AND sort_order=7);

-- old row #7 'תורה - נביאים - כתובים'
INSERT INTO rabbi_page_items (rabbi_id, kind, lesson_id, sort_order)
SELECT 'e6c81665-5737-4c82-b96e-7527cc0e6ee6', 'lesson', '526ade3e-5a79-449c-b851-706a64428cf8', 8
WHERE NOT EXISTS (SELECT 1 FROM rabbi_page_items WHERE rabbi_id='e6c81665-5737-4c82-b96e-7527cc0e6ee6' AND lesson_id='526ade3e-5a79-449c-b851-706a64428cf8' AND sort_order=8);

-- old row #29 'האם דניאל היה נביא?'
INSERT INTO rabbi_page_items (rabbi_id, kind, lesson_id, sort_order)
SELECT 'e6c81665-5737-4c82-b96e-7527cc0e6ee6', 'lesson', '6b7c29ba-96aa-59cf-a264-79f0b8fb6b79', 30
WHERE NOT EXISTS (SELECT 1 FROM rabbi_page_items WHERE rabbi_id='e6c81665-5737-4c82-b96e-7527cc0e6ee6' AND lesson_id='6b7c29ba-96aa-59cf-a264-79f0b8fb6b79' AND sort_order=30);

-- old row #33 'על מה נצטוו ישראל במרה?'
INSERT INTO rabbi_page_items (rabbi_id, kind, lesson_id, sort_order)
SELECT 'e6c81665-5737-4c82-b96e-7527cc0e6ee6', 'lesson', '7dae3eca-08e8-4b32-8754-fa7e48568dd9', 34
WHERE NOT EXISTS (SELECT 1 FROM rabbi_page_items WHERE rabbi_id='e6c81665-5737-4c82-b96e-7527cc0e6ee6' AND lesson_id='7dae3eca-08e8-4b32-8754-fa7e48568dd9' AND sort_order=34);

-- old row #39 'שורש מלחמת דוד וגלית'
INSERT INTO rabbi_page_items (rabbi_id, kind, lesson_id, sort_order)
SELECT 'e6c81665-5737-4c82-b96e-7527cc0e6ee6', 'lesson', '92094505-7c5f-4dbd-bc38-b8457fc6798b', 40
WHERE NOT EXISTS (SELECT 1 FROM rabbi_page_items WHERE rabbi_id='e6c81665-5737-4c82-b96e-7527cc0e6ee6' AND lesson_id='92094505-7c5f-4dbd-bc38-b8457fc6798b' AND sort_order=40);

-- verification: in-band ladder size (expect 40; old rows 40 minus 0 yoav minus 0 sanctioned-missing)
SELECT count(*) AS v_e6c81665_inband FROM rabbi_page_items WHERE rabbi_id = 'e6c81665-5737-4c82-b96e-7527cc0e6ee6' AND sort_order < 9000;
-- verification: parked rows (expect 0)
SELECT count(*) AS v_e6c81665_parked FROM rabbi_page_items WHERE rabbi_id = 'e6c81665-5737-4c82-b96e-7527cc0e6ee6' AND sort_order >= 9000;
-- verification: no in-band slot collisions (expect 0)
SELECT count(*) AS v_e6c81665_collisions FROM (SELECT sort_order FROM rabbi_page_items WHERE rabbi_id='e6c81665-5737-4c82-b96e-7527cc0e6ee6' AND sort_order<9000 GROUP BY sort_order HAVING count(*)>1) q;

-- ============================================================================
-- §מערכת בני ציון  (rabbi_id 274f4480-cc34-4331-842e-138c2e1f6175)
--   old rows: 8 · live rpi: 6 · pairs: 6 · inserts: 0 · parks: 0 · yoav: 2 · sanctioned-missing: 0
-- ----------------------------------------------------------------------------
-- verification: in-band ladder size (expect 6; old rows 8 minus 2 yoav minus 0 sanctioned-missing)
SELECT count(*) AS v_274f4480_inband FROM rabbi_page_items WHERE rabbi_id = '274f4480-cc34-4331-842e-138c2e1f6175' AND sort_order < 9000;
-- verification: parked rows (expect 0)
SELECT count(*) AS v_274f4480_parked FROM rabbi_page_items WHERE rabbi_id = '274f4480-cc34-4331-842e-138c2e1f6175' AND sort_order >= 9000;
-- verification: no in-band slot collisions (expect 0)
SELECT count(*) AS v_274f4480_collisions FROM (SELECT sort_order FROM rabbi_page_items WHERE rabbi_id='274f4480-cc34-4331-842e-138c2e1f6175' AND sort_order<9000 GROUP BY sort_order HAVING count(*)>1) q;

