// Originally generated by Lovable; kept stable so we can ship overrides.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// HARDCODED ON PURPOSE — NetSpark MITM outage prevention.
// Background (battle-tested on Aboulafia 4-May-2026, same pattern applied here):
// Vercel builds on networks behind a transparent TLS-intercepting proxy (NetSpark)
// can emit bundles where `import.meta.env.VITE_SUPABASE_URL` is stripped/empty,
// even though the env var is correctly set in the Vercel dashboard.
// The Supabase client then throws "supabaseUrl is required" at module load and
// kills the entire React app on every route — homepage, /checkout, everything.
//
// These two values are PUBLIC (project URL + anon/publishable key — already
// shipped to the browser in any build) so embedding them is safe and removes
// a class of "site is down because env var didn't propagate" outages.
//
// To rotate keys: update both constants and re-deploy.
const SUPABASE_URL = "https://pzvmwfexeiruelwiujxn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6dm13ZmV4ZWlydWVsd2l1anhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU1NTM1NzUsImV4cCI6MjA5MTEyOTU3NX0.U5agLkf6jfLUg7UjfdnTJfavUsx-dyzxs2fxJgWAp8o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});