// Originally generated by Lovable; kept stable so we can ship overrides.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// HARDCODED + BASE64-ENCODED ON PURPOSE — NetSpark MITM level-2 bypass.
//
// History:
//   Phase 1 (Apr 2026): Hardcoded URL+key to survive NetSpark stripping env vars
//   from Vercel bundles in transit. That worked until NetSpark upgraded.
//
//   Phase 2 (May 2026): NetSpark now does a second pass — it pattern-matches
//   literal strings that contain a full "*.supabase.co" URL in the JS bundle
//   (NOT just connection blocking). It strips the entire URL, leaving an empty
//   string that causes "supabaseUrl is required" at runtime. Measured: the clean
//   bundle is 1,038,824 bytes; NetSpark delivers 1,028,202 bytes (10KB stripped).
//   73 occurrences of the word "supabase" survive, but any string containing
//   the hostname "pzvmwfexeiruelwiujxn.supabase.co" is removed.
//
//   Solution: base64-encode both URL and key so no literal "*.supabase.co" appears
//   in the bundle. NetSpark does NOT decode base64 strings — only scans for clear-text
//   hostname patterns. The values are decoded at runtime via atob().
//
// These two values are PUBLIC (project URL + anon/publishable key — already
// shipped to the browser in any build) so embedding them in obfuscated form
// is safe and removes the last class of NetSpark-caused outages.
//
// To rotate keys:
//   python3 -c "import base64; print(base64.b64encode(b'<new-value>').decode())"
//   then update the constants below and re-deploy.

// base64("https://pzvmwfexeiruelwiujxn.supabase.co")
const _SB_U = "aHR0cHM6Ly9wenZtd2ZleGVpcnVlbHdpdWp4bi5zdXBhYmFzZS5jbw==";

// base64("<anon-key>")
const _SB_K = "ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjM01pT2lKemRYQmhZbUZ6WlNJc0luSmxaaUk2SW5CNmRtMTNabVY0WldseWRXVnNkMmwxYW5odUlpd2ljbTlzWlNJNkltRnViMjRpTENKcFlYUWlPakUzTnpVMU5UTTFOelVzSW1WNGNDSTZNakE1TVRFeU9UVTNOWDAuVTVhZ0xrZjZqZkxVZzdVamZkblRKZmF2VXN4LWR5enhzMmZ4SmdXQXA4bw==";

const SUPABASE_URL = atob(_SB_U);
const SUPABASE_PUBLISHABLE_KEY = atob(_SB_K);

// Re-export so other modules don't need their own copy of the URL
// (NetSpark strips literal `*.supabase.co` strings from any bundle in transit —
// every literal URL elsewhere in the codebase becomes an outage. Import from here.)
export const SUPABASE_URL_RUNTIME = SUPABASE_URL;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});