-- ============================================================================
-- plan_ויקרא.sql  —  Bnei-Zion 1:1 migration · REVIEW ROUND 1 · book = ויקרא
-- Generated by parity agent. IDEMPOTENT / GUARDED. DO NOT auto-execute.
-- Ground truth: old category page https://www.bneyzion.co.il/מאגר-השיעורים-והמאמרים/תורה/ויקרא/
-- DB project: pzvmwfexeiruelwiujxn (bnei-zion)
--
-- SCOPE (verify before running):
--   Category 'ויקרא' = series.status='category', parent='תורה'.
--   22/22 old rabbi-series matched to NEW series (all exact-title). 20 OK.
--   1 UNDERFILLED: 'קדושת פשוטו של מקרא - ויקרא' (קופרמן)  old=17 new=0  -> backfill 17 PDF lessons (THIS FILE).
--   1 OVERFILLED : 'שיעורים- חומש ויקרא' (תירוש)          old=25 new=26 -> in-series exact dup 'עבד עברי' (display-dedup, NO delete).
--   Standalone/שו"ת (15+7=22): ALL already exist in DB (nested under parsha-event-series / aggregation). 0 inserts. CODE surfaces them.
--   10 parsha event-series present (Vayikra has exactly 10 parshiyot) -> sidebar nodes, CODE excludes from category rows.
-- ============================================================================

BEGIN;

-- ---------------------------------------------------------------------------
-- SCOPING SELECTS (run first, eyeball, must each return the expected value)
-- ---------------------------------------------------------------------------
-- [S1] target series exists, is the empty Kuperman Vayikra series, correct rabbi
SELECT id, title, status, rabbi_id,
       (SELECT count(*) FROM lessons l WHERE l.series_id = s.id) AS cur_lessons
  FROM series s
 WHERE s.id = '155c726f-a725-555a-a173-b51671bc36a8';  -- expect title='קדושת פשוטו של מקרא - ויקרא', rabbi_id='9135d874-b42b-4952-b7c6-97f0fb7fbfe6', cur_lessons=0

-- [S2] confirm the series sits under the ויקרא category under תורה
SELECT s.id, s.title, p.title AS parent, gp.title AS grandparent
  FROM series s JOIN series p ON p.id = s.parent_id JOIN series gp ON gp.id = p.parent_id
 WHERE s.id = '155c726f-a725-555a-a173-b51671bc36a8';  -- expect parent='ויקרא', grandparent='תורה'

-- [S3] confirm rabbi name
SELECT id, name FROM rabbis WHERE id = '9135d874-b42b-4952-b7c6-97f0fb7fbfe6';  -- expect 'הרב יהודה קופרמן זצ"ל'

-- ---------------------------------------------------------------------------
-- PART B.1 — BACKFILL 17 lessons into empty Kuperman series (UNDERFILLED fix)
-- Source: old series page rows. All media = bneyzion.co.il/media/*.pdf  -> Rule 13 REHOST.
--   legacy_attachment_url = gold key (kept verbatim from old site, used for idempotency + rehost worker).
--   attachment_url        = SAME url for now; rehost worker rewrites to Storage later.
--   source_type='text', status='published', bible_book='ויקרא', rabbi_id=Kuperman.
-- Guard: INSERT ... WHERE NOT EXISTS (same series_id + same legacy_attachment_url). Re-run = no-op.
-- ---------------------------------------------------------------------------

-- [ 1] על מקום כתיבת מצוה בתורה
INSERT INTO lessons (id, title, rabbi_id, series_id, source_type, status,
                     bible_book, attachment_url, legacy_attachment_url, sort_order,
                     audience_tags, published_at, created_at, updated_at)
SELECT gen_random_uuid(),
       'על מקום כתיבת מצוה בתורה',
       '9135d874-b42b-4952-b7c6-97f0fb7fbfe6',
       '155c726f-a725-555a-a173-b51671bc36a8',
       'text', 'published',
       'ויקרא',
       'https://www.bneyzion.co.il/media/143243/קדושת-פשוטו-של-מקרא-ויקרא1-5.pdf',  -- REHOST: bneyzion.co.il PDF, rewrite to Storage
       'https://www.bneyzion.co.il/media/143243/קדושת-פשוטו-של-מקרא-ויקרא1-5.pdf',  -- legacy gold key
       10,
       ARRAY['general'], now(), now(), now()
WHERE NOT EXISTS (
  SELECT 1 FROM lessons x
   WHERE x.series_id = '155c726f-a725-555a-a173-b51671bc36a8'
     AND x.legacy_attachment_url = 'https://www.bneyzion.co.il/media/143243/קדושת-פשוטו-של-מקרא-ויקרא1-5.pdf'
);

-- [ 2] עבר פשוט כעבר מוקדם
INSERT INTO lessons (id, title, rabbi_id, series_id, source_type, status,
                     bible_book, attachment_url, legacy_attachment_url, sort_order,
                     audience_tags, published_at, created_at, updated_at)
SELECT gen_random_uuid(),
       'עבר פשוט כעבר מוקדם',
       '9135d874-b42b-4952-b7c6-97f0fb7fbfe6',
       '155c726f-a725-555a-a173-b51671bc36a8',
       'text', 'published',
       'ויקרא',
       'https://www.bneyzion.co.il/media/143246/קדושת-פשוטו-של-מקרא-ויקרא6-9.pdf',  -- REHOST: bneyzion.co.il PDF, rewrite to Storage
       'https://www.bneyzion.co.il/media/143246/קדושת-פשוטו-של-מקרא-ויקרא6-9.pdf',  -- legacy gold key
       20,
       ARRAY['general'], now(), now(), now()
WHERE NOT EXISTS (
  SELECT 1 FROM lessons x
   WHERE x.series_id = '155c726f-a725-555a-a173-b51671bc36a8'
     AND x.legacy_attachment_url = 'https://www.bneyzion.co.il/media/143246/קדושת-פשוטו-של-מקרא-ויקרא6-9.pdf'
);

-- [ 3] שלימות התורה (הלכה - מחשבה - פרשנות)
INSERT INTO lessons (id, title, rabbi_id, series_id, source_type, status,
                     bible_book, attachment_url, legacy_attachment_url, sort_order,
                     audience_tags, published_at, created_at, updated_at)
SELECT gen_random_uuid(),
       'שלימות התורה (הלכה - מחשבה - פרשנות)',
       '9135d874-b42b-4952-b7c6-97f0fb7fbfe6',
       '155c726f-a725-555a-a173-b51671bc36a8',
       'text', 'published',
       'ויקרא',
       'https://www.bneyzion.co.il/media/143247/קדושת-פשוטו-של-מקרא-ויקרא10-14.pdf',  -- REHOST: bneyzion.co.il PDF, rewrite to Storage
       'https://www.bneyzion.co.il/media/143247/קדושת-פשוטו-של-מקרא-ויקרא10-14.pdf',  -- legacy gold key
       30,
       ARRAY['general'], now(), now(), now()
WHERE NOT EXISTS (
  SELECT 1 FROM lessons x
   WHERE x.series_id = '155c726f-a725-555a-a173-b51671bc36a8'
     AND x.legacy_attachment_url = 'https://www.bneyzion.co.il/media/143247/קדושת-פשוטו-של-מקרא-ויקרא10-14.pdf'
);

-- [ 4] הלכה לשעה דאורייתא
INSERT INTO lessons (id, title, rabbi_id, series_id, source_type, status,
                     bible_book, attachment_url, legacy_attachment_url, sort_order,
                     audience_tags, published_at, created_at, updated_at)
SELECT gen_random_uuid(),
       'הלכה לשעה דאורייתא',
       '9135d874-b42b-4952-b7c6-97f0fb7fbfe6',
       '155c726f-a725-555a-a173-b51671bc36a8',
       'text', 'published',
       'ויקרא',
       'https://www.bneyzion.co.il/media/143248/קדושת-פשוטו-של-מקרא-צו1-4.pdf',  -- REHOST: bneyzion.co.il PDF, rewrite to Storage
       'https://www.bneyzion.co.il/media/143248/קדושת-פשוטו-של-מקרא-צו1-4.pdf',  -- legacy gold key
       40,
       ARRAY['general'], now(), now(), now()
WHERE NOT EXISTS (
  SELECT 1 FROM lessons x
   WHERE x.series_id = '155c726f-a725-555a-a173-b51671bc36a8'
     AND x.legacy_attachment_url = 'https://www.bneyzion.co.il/media/143248/קדושת-פשוטו-של-מקרא-צו1-4.pdf'
);

-- [ 5] עבר פשוט כעבר מוקדם במשנתו של הרמב"ן
INSERT INTO lessons (id, title, rabbi_id, series_id, source_type, status,
                     bible_book, attachment_url, legacy_attachment_url, sort_order,
                     audience_tags, published_at, created_at, updated_at)
SELECT gen_random_uuid(),
       'עבר פשוט כעבר מוקדם במשנתו של הרמב"ן',
       '9135d874-b42b-4952-b7c6-97f0fb7fbfe6',
       '155c726f-a725-555a-a173-b51671bc36a8',
       'text', 'published',
       'ויקרא',
       'https://www.bneyzion.co.il/media/143251/קדושת-פשוטו-של-מקרא-צו5-8.pdf',  -- REHOST: bneyzion.co.il PDF, rewrite to Storage
       'https://www.bneyzion.co.il/media/143251/קדושת-פשוטו-של-מקרא-צו5-8.pdf',  -- legacy gold key
       50,
       ARRAY['general'], now(), now(), now()
WHERE NOT EXISTS (
  SELECT 1 FROM lessons x
   WHERE x.series_id = '155c726f-a725-555a-a173-b51671bc36a8'
     AND x.legacy_attachment_url = 'https://www.bneyzion.co.il/media/143251/קדושת-פשוטו-של-מקרא-צו5-8.pdf'
);

-- [ 6] קרבן תודה - המצוה המורכבת
INSERT INTO lessons (id, title, rabbi_id, series_id, source_type, status,
                     bible_book, attachment_url, legacy_attachment_url, sort_order,
                     audience_tags, published_at, created_at, updated_at)
SELECT gen_random_uuid(),
       'קרבן תודה - המצוה המורכבת',
       '9135d874-b42b-4952-b7c6-97f0fb7fbfe6',
       '155c726f-a725-555a-a173-b51671bc36a8',
       'text', 'published',
       'ויקרא',
       'https://www.bneyzion.co.il/media/143252/קדושת-פשוטו-של-מקרא-צו9-10.pdf',  -- REHOST: bneyzion.co.il PDF, rewrite to Storage
       'https://www.bneyzion.co.il/media/143252/קדושת-פשוטו-של-מקרא-צו9-10.pdf',  -- legacy gold key
       60,
       ARRAY['general'], now(), now(), now()
WHERE NOT EXISTS (
  SELECT 1 FROM lessons x
   WHERE x.series_id = '155c726f-a725-555a-a173-b51671bc36a8'
     AND x.legacy_attachment_url = 'https://www.bneyzion.co.il/media/143252/קדושת-פשוטו-של-מקרא-צו9-10.pdf'
);

-- [ 7] לפני ואחרי במשנת רבנו עובדיה ספורנו
INSERT INTO lessons (id, title, rabbi_id, series_id, source_type, status,
                     bible_book, attachment_url, legacy_attachment_url, sort_order,
                     audience_tags, published_at, created_at, updated_at)
SELECT gen_random_uuid(),
       'לפני ואחרי במשנת רבנו עובדיה ספורנו',
       '9135d874-b42b-4952-b7c6-97f0fb7fbfe6',
       '155c726f-a725-555a-a173-b51671bc36a8',
       'text', 'published',
       'ויקרא',
       'https://www.bneyzion.co.il/media/143153/קדושת-פשוטו-של-מקרא-שמיני.pdf',  -- REHOST: bneyzion.co.il PDF, rewrite to Storage
       'https://www.bneyzion.co.il/media/143153/קדושת-פשוטו-של-מקרא-שמיני.pdf',  -- legacy gold key
       70,
       ARRAY['general'], now(), now(), now()
WHERE NOT EXISTS (
  SELECT 1 FROM lessons x
   WHERE x.series_id = '155c726f-a725-555a-a173-b51671bc36a8'
     AND x.legacy_attachment_url = 'https://www.bneyzion.co.il/media/143153/קדושת-פשוטו-של-מקרא-שמיני.pdf'
);

-- [ 8] דרכיה דרכי נועם
INSERT INTO lessons (id, title, rabbi_id, series_id, source_type, status,
                     bible_book, attachment_url, legacy_attachment_url, sort_order,
                     audience_tags, published_at, created_at, updated_at)
SELECT gen_random_uuid(),
       'דרכיה דרכי נועם',
       '9135d874-b42b-4952-b7c6-97f0fb7fbfe6',
       '155c726f-a725-555a-a173-b51671bc36a8',
       'text', 'published',
       'ויקרא',
       'https://www.bneyzion.co.il/media/143154/קדושת-פשוטו-של-מקרא-תזריע.pdf',  -- REHOST: bneyzion.co.il PDF, rewrite to Storage
       'https://www.bneyzion.co.il/media/143154/קדושת-פשוטו-של-מקרא-תזריע.pdf',  -- legacy gold key
       80,
       ARRAY['general'], now(), now(), now()
WHERE NOT EXISTS (
  SELECT 1 FROM lessons x
   WHERE x.series_id = '155c726f-a725-555a-a173-b51671bc36a8'
     AND x.legacy_attachment_url = 'https://www.bneyzion.co.il/media/143154/קדושת-פשוטו-של-מקרא-תזריע.pdf'
);

-- [ 9] סדר עבודת יום הכיפורים לשעה לדורות ולנצח
INSERT INTO lessons (id, title, rabbi_id, series_id, source_type, status,
                     bible_book, attachment_url, legacy_attachment_url, sort_order,
                     audience_tags, published_at, created_at, updated_at)
SELECT gen_random_uuid(),
       'סדר עבודת יום הכיפורים לשעה לדורות ולנצח',
       '9135d874-b42b-4952-b7c6-97f0fb7fbfe6',
       '155c726f-a725-555a-a173-b51671bc36a8',
       'text', 'published',
       'ויקרא',
       'https://www.bneyzion.co.il/media/143253/קדושת-פשוטו-של-מקרא-אחרי-מות.pdf',  -- REHOST: bneyzion.co.il PDF, rewrite to Storage
       'https://www.bneyzion.co.il/media/143253/קדושת-פשוטו-של-מקרא-אחרי-מות.pdf',  -- legacy gold key
       90,
       ARRAY['general'], now(), now(), now()
WHERE NOT EXISTS (
  SELECT 1 FROM lessons x
   WHERE x.series_id = '155c726f-a725-555a-a173-b51671bc36a8'
     AND x.legacy_attachment_url = 'https://www.bneyzion.co.il/media/143253/קדושת-פשוטו-של-מקרא-אחרי-מות.pdf'
);

-- [10] לפני ואחרי במשנת רבנו עובדיה ספורנו - איסור עריות
INSERT INTO lessons (id, title, rabbi_id, series_id, source_type, status,
                     bible_book, attachment_url, legacy_attachment_url, sort_order,
                     audience_tags, published_at, created_at, updated_at)
SELECT gen_random_uuid(),
       'לפני ואחרי במשנת רבנו עובדיה ספורנו - איסור עריות',
       '9135d874-b42b-4952-b7c6-97f0fb7fbfe6',
       '155c726f-a725-555a-a173-b51671bc36a8',
       'text', 'published',
       'ויקרא',
       'https://www.bneyzion.co.il/media/143255/קדושת-פשוטו-של-מקרא-אחרי-מות-2.pdf',  -- REHOST: bneyzion.co.il PDF, rewrite to Storage
       'https://www.bneyzion.co.il/media/143255/קדושת-פשוטו-של-מקרא-אחרי-מות-2.pdf',  -- legacy gold key
       100,
       ARRAY['general'], now(), now(), now()
WHERE NOT EXISTS (
  SELECT 1 FROM lessons x
   WHERE x.series_id = '155c726f-a725-555a-a173-b51671bc36a8'
     AND x.legacy_attachment_url = 'https://www.bneyzion.co.il/media/143255/קדושת-פשוטו-של-מקרא-אחרי-מות-2.pdf'
);

-- [11] כבודו של יעקב וכבודו של עמרם
INSERT INTO lessons (id, title, rabbi_id, series_id, source_type, status,
                     bible_book, attachment_url, legacy_attachment_url, sort_order,
                     audience_tags, published_at, created_at, updated_at)
SELECT gen_random_uuid(),
       'כבודו של יעקב וכבודו של עמרם',
       '9135d874-b42b-4952-b7c6-97f0fb7fbfe6',
       '155c726f-a725-555a-a173-b51671bc36a8',
       'text', 'published',
       'ויקרא',
       'https://www.bneyzion.co.il/media/143256/קדושת-פשוטו-של-מקרא-קדושים1-6.pdf',  -- REHOST: bneyzion.co.il PDF, rewrite to Storage
       'https://www.bneyzion.co.il/media/143256/קדושת-פשוטו-של-מקרא-קדושים1-6.pdf',  -- legacy gold key
       110,
       ARRAY['general'], now(), now(), now()
WHERE NOT EXISTS (
  SELECT 1 FROM lessons x
   WHERE x.series_id = '155c726f-a725-555a-a173-b51671bc36a8'
     AND x.legacy_attachment_url = 'https://www.bneyzion.co.il/media/143256/קדושת-פשוטו-של-מקרא-קדושים1-6.pdf'
);

-- [12] לאו שבכללות ופשוטו של מקרא
INSERT INTO lessons (id, title, rabbi_id, series_id, source_type, status,
                     bible_book, attachment_url, legacy_attachment_url, sort_order,
                     audience_tags, published_at, created_at, updated_at)
SELECT gen_random_uuid(),
       'לאו שבכללות ופשוטו של מקרא',
       '9135d874-b42b-4952-b7c6-97f0fb7fbfe6',
       '155c726f-a725-555a-a173-b51671bc36a8',
       'text', 'published',
       'ויקרא',
       'https://www.bneyzion.co.il/media/143258/קדושת-פשוטו-של-מקרא-קדושים7-13.pdf',  -- REHOST: bneyzion.co.il PDF, rewrite to Storage
       'https://www.bneyzion.co.il/media/143258/קדושת-פשוטו-של-מקרא-קדושים7-13.pdf',  -- legacy gold key
       120,
       ARRAY['general'], now(), now(), now()
WHERE NOT EXISTS (
  SELECT 1 FROM lessons x
   WHERE x.series_id = '155c726f-a725-555a-a173-b51671bc36a8'
     AND x.legacy_attachment_url = 'https://www.bneyzion.co.il/media/143258/קדושת-פשוטו-של-מקרא-קדושים7-13.pdf'
);

-- [13] אין מקרא יוצא מדי פשוטו
INSERT INTO lessons (id, title, rabbi_id, series_id, source_type, status,
                     bible_book, attachment_url, legacy_attachment_url, sort_order,
                     audience_tags, published_at, created_at, updated_at)
SELECT gen_random_uuid(),
       'אין מקרא יוצא מדי פשוטו',
       '9135d874-b42b-4952-b7c6-97f0fb7fbfe6',
       '155c726f-a725-555a-a173-b51671bc36a8',
       'text', 'published',
       'ויקרא',
       'https://www.bneyzion.co.il/media/143259/קדושת-פשוטו-של-מקרא-אמור_1-7.pdf',  -- REHOST: bneyzion.co.il PDF, rewrite to Storage
       'https://www.bneyzion.co.il/media/143259/קדושת-פשוטו-של-מקרא-אמור_1-7.pdf',  -- legacy gold key
       130,
       ARRAY['general'], now(), now(), now()
WHERE NOT EXISTS (
  SELECT 1 FROM lessons x
   WHERE x.series_id = '155c726f-a725-555a-a173-b51671bc36a8'
     AND x.legacy_attachment_url = 'https://www.bneyzion.co.il/media/143259/קדושת-פשוטו-של-מקרא-אמור_1-7.pdf'
);

-- [14] משמעות מילה לפי מקום כתיבתה בתורה
INSERT INTO lessons (id, title, rabbi_id, series_id, source_type, status,
                     bible_book, attachment_url, legacy_attachment_url, sort_order,
                     audience_tags, published_at, created_at, updated_at)
SELECT gen_random_uuid(),
       'משמעות מילה לפי מקום כתיבתה בתורה',
       '9135d874-b42b-4952-b7c6-97f0fb7fbfe6',
       '155c726f-a725-555a-a173-b51671bc36a8',
       'text', 'published',
       'ויקרא',
       'https://www.bneyzion.co.il/media/143261/קדושת-פשוטו-של-מקרא-אמור_8-10.pdf',  -- REHOST: bneyzion.co.il PDF, rewrite to Storage
       'https://www.bneyzion.co.il/media/143261/קדושת-פשוטו-של-מקרא-אמור_8-10.pdf',  -- legacy gold key
       140,
       ARRAY['general'], now(), now(), now()
WHERE NOT EXISTS (
  SELECT 1 FROM lessons x
   WHERE x.series_id = '155c726f-a725-555a-a173-b51671bc36a8'
     AND x.legacy_attachment_url = 'https://www.bneyzion.co.il/media/143261/קדושת-פשוטו-של-מקרא-אמור_8-10.pdf'
);

-- [15] "ואני לא באתי אלא לפרש פשוטו של מקרא"
INSERT INTO lessons (id, title, rabbi_id, series_id, source_type, status,
                     bible_book, attachment_url, legacy_attachment_url, sort_order,
                     audience_tags, published_at, created_at, updated_at)
SELECT gen_random_uuid(),
       '"ואני לא באתי אלא לפרש פשוטו של מקרא"',
       '9135d874-b42b-4952-b7c6-97f0fb7fbfe6',
       '155c726f-a725-555a-a173-b51671bc36a8',
       'text', 'published',
       'ויקרא',
       'https://www.bneyzion.co.il/media/143262/קדושת-פשוטו-של-מקרא-בהר_1-5.pdf',  -- REHOST: bneyzion.co.il PDF, rewrite to Storage
       'https://www.bneyzion.co.il/media/143262/קדושת-פשוטו-של-מקרא-בהר_1-5.pdf',  -- legacy gold key
       150,
       ARRAY['general'], now(), now(), now()
WHERE NOT EXISTS (
  SELECT 1 FROM lessons x
   WHERE x.series_id = '155c726f-a725-555a-a173-b51671bc36a8'
     AND x.legacy_attachment_url = 'https://www.bneyzion.co.il/media/143262/קדושת-פשוטו-של-מקרא-בהר_1-5.pdf'
);

-- [16] "עמך במאכל, עמך במשתה" - ציווי או סיפור
INSERT INTO lessons (id, title, rabbi_id, series_id, source_type, status,
                     bible_book, attachment_url, legacy_attachment_url, sort_order,
                     audience_tags, published_at, created_at, updated_at)
SELECT gen_random_uuid(),
       '"עמך במאכל, עמך במשתה" - ציווי או סיפור',
       '9135d874-b42b-4952-b7c6-97f0fb7fbfe6',
       '155c726f-a725-555a-a173-b51671bc36a8',
       'text', 'published',
       'ויקרא',
       'https://www.bneyzion.co.il/media/143264/קדושת-פשוטו-של-מקרא-בהר_6-8.pdf',  -- REHOST: bneyzion.co.il PDF, rewrite to Storage
       'https://www.bneyzion.co.il/media/143264/קדושת-פשוטו-של-מקרא-בהר_6-8.pdf',  -- legacy gold key
       160,
       ARRAY['general'], now(), now(), now()
WHERE NOT EXISTS (
  SELECT 1 FROM lessons x
   WHERE x.series_id = '155c726f-a725-555a-a173-b51671bc36a8'
     AND x.legacy_attachment_url = 'https://www.bneyzion.co.il/media/143264/קדושת-פשוטו-של-מקרא-בהר_6-8.pdf'
);

-- [17] פשט ומדרש מלמדים הלכה יחדיו
INSERT INTO lessons (id, title, rabbi_id, series_id, source_type, status,
                     bible_book, attachment_url, legacy_attachment_url, sort_order,
                     audience_tags, published_at, created_at, updated_at)
SELECT gen_random_uuid(),
       'פשט ומדרש מלמדים הלכה יחדיו',
       '9135d874-b42b-4952-b7c6-97f0fb7fbfe6',
       '155c726f-a725-555a-a173-b51671bc36a8',
       'text', 'published',
       'ויקרא',
       'https://www.bneyzion.co.il/media/143265/קדושת-פשוטו-של-מקרא-בחוקתי.pdf',  -- REHOST: bneyzion.co.il PDF, rewrite to Storage
       'https://www.bneyzion.co.il/media/143265/קדושת-פשוטו-של-מקרא-בחוקתי.pdf',  -- legacy gold key
       170,
       ARRAY['general'], now(), now(), now()
WHERE NOT EXISTS (
  SELECT 1 FROM lessons x
   WHERE x.series_id = '155c726f-a725-555a-a173-b51671bc36a8'
     AND x.legacy_attachment_url = 'https://www.bneyzion.co.il/media/143265/קדושת-פשוטו-של-מקרא-בחוקתי.pdf'
);

-- ---------------------------------------------------------------------------
-- PART B.2 — OVERFILLED 'שיעורים- חומש ויקרא' (תירוש)  old=25 new=26
--   Exact in-series duplicate: title='עבד עברי' appears TWICE, identical audio_url.
--     keep canonical (older created_at): id=74c38a37-6c6e-4dc6-afb6-4c01bd87486e (2026-02-23)
--     duplicate                        : id=9de08b75-7a9e-466c-ba52-7b6ebc5ebbaa (2026-03-15, sort_order=260)
--   POLICY (project precedent): DISPLAY-DEDUP, do NOT physical-delete. Recorded here for the code/display layer.
--   If Saar later approves physical removal, the guarded delete is below (commented out).
-- ---------------------------------------------------------------------------
-- Verify the duplicate pair before any action:
SELECT id, title, sort_order, audio_url, created_at
  FROM lessons
 WHERE series_id = 'd73c8425-d2ec-4cb7-9857-0f02e03a12f6' AND title = 'עבד עברי'
 ORDER BY created_at;  -- expect 2 rows, identical audio_url

-- (DISABLED — needs explicit Saar approval; physical delete of the newer dup)
-- DELETE FROM lessons
--  WHERE id = '9de08b75-7a9e-466c-ba52-7b6ebc5ebbaa'
--    AND series_id = 'd73c8425-d2ec-4cb7-9857-0f02e03a12f6'
--    AND title = 'עבד עברי'
--    AND EXISTS (SELECT 1 FROM lessons o WHERE o.id='74c38a37-6c6e-4dc6-afb6-4c01bd87486e'
--                  AND o.title='עבד עברי' AND o.audio_url = lessons.audio_url);

-- ---------------------------------------------------------------------------
-- PART C — standalone + שו"ת (22 old-page rows): NO INSERTS.
--   All 22 already exist in DB (each with >=1 copy bible_book='ויקרא'), nested under
--   parsha-event-series / 'ספר ויקרא עם ביאור ושננתם' aggregation. 0 rows have series_id IS NULL.
--   Surfacing them as flat category rows is a CODE concern (query lessons by bible_book + parsha-series,
--   dedup by normalized title). Inserting standalone copies here would create REAL duplicates -> skipped.
-- ---------------------------------------------------------------------------

-- ---------------------------------------------------------------------------
-- VERIFICATION (run AFTER inserts; all must pass)
-- ---------------------------------------------------------------------------
-- [V1] Kuperman series now has 17 published lessons
SELECT count(*) AS kuperman_published FROM lessons
 WHERE series_id = '155c726f-a725-555a-a173-b51671bc36a8' AND status = 'published';  -- expect 17

-- [V2] no duplicate legacy urls inside the Kuperman series
SELECT legacy_attachment_url, count(*) FROM lessons
 WHERE series_id = '155c726f-a725-555a-a173-b51671bc36a8' GROUP BY 1 HAVING count(*) > 1;  -- expect 0 rows

-- [V3] sort_order 10..170 present and unique
SELECT count(DISTINCT sort_order) AS distinct_so FROM lessons WHERE series_id='155c726f-a725-555a-a173-b51671bc36a8';  -- expect 17

-- [V4] all 17 flagged for rehost (bneyzion.co.il media)
SELECT count(*) AS to_rehost FROM lessons
 WHERE series_id='155c726f-a725-555a-a173-b51671bc36a8' AND legacy_attachment_url LIKE '%bneyzion.co.il/media/%';  -- expect 17

-- [V5] category child series count sanity (rabbi-series + parsha + teacher nodes)
SELECT count(*) FROM series WHERE parent_id = (
  SELECT id FROM series WHERE title='ויקרא' AND status='category'
    AND parent_id=(SELECT id FROM series WHERE title='תורה' AND parent_id IS NULL));  -- baseline 33 (22 rabbi-series + 10 parsha-event + 1 teacher node 'דפי עבודה - ויקרא')

COMMIT;
-- ROLLBACK;  -- use instead of COMMIT for a dry run
